"use client";
import {useState} from 'react';
import {Check,ChevronDown,ChevronLeft,ChevronRight,Clock,MapPin} from 'lucide-react';
import {Button} from './ui/button';
import './studio.css';
export const appointments=[
 {name:'Surface consultation',minutes:30,color:'#a7ea31',description:'Explore your walls, cabinets, countertops and surface transformation options.',location:'Phone call'},
 {name:'Design consultation',minutes:45,color:'#38bdf8',description:'Materials, colors, custom graphics, wallpaper and finish selections.',location:'Video or phone'},
 {name:'Architectural wrap consultation',minutes:60,color:'#e9a42a',description:'Cabinets, doors, counters and commercial surfaces, measurements and preparation.',location:'Project consultation'},
 {name:'Window tint / film consultation',minutes:60,color:'#39bd72',description:'Privacy, solar control and decorative film for residential and commercial glass.',location:'Project consultation'},
 {name:'Installation consultation',minutes:90,color:'#f17f22',description:'Site access, preparation, measurements, scope and installation planning.',location:'Site details confirmed by team'},
 {name:'Roman clay / decorative finish',minutes:45,color:'#bb977c',description:'Texture, colors, substrate condition and decorative finish options.',location:'Project consultation'},
 {name:'Artwork / proof review',minutes:30,color:'#b18cf4',description:'Review graphics, artwork dimensions, proofs and production requirements.',location:'Video or phone'},
];
export function BookingChoices({step,service,setService,date,setDate,time,setTime,next,back}:{step:number;service:string;setService:(s:string)=>void;date:string;setDate:(s:string)=>void;time:string;setTime:(s:string)=>void;next:()=>void;back:()=>void}){
 const today=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Phoenix'}).format(new Date());
 const[month,setMonth]=useState((date||today).slice(0,7));
 const selected=appointments.find(a=>a.name===service)||appointments[0];
 const first=new Date(`${month}-01T12:00:00Z`),days=new Date(Date.UTC(first.getUTCFullYear(),first.getUTCMonth()+1,0)).getUTCDate();
 function move(n:number){const d=new Date(first);d.setUTCMonth(d.getUTCMonth()+n);setMonth(d.toISOString().slice(0,7));}
 return step===1?<><h2>Choose appointment type</h2><p>Select the service that best fits what you need.</p><div className="booking-types">{appointments.map(a=><button key={a.name} aria-expanded={service===a.name} aria-pressed={service===a.name} onClick={()=>setService(a.name)}><span className="booking-type-top"><span className="booking-radio">{service===a.name&&<Check size={15}/>}</span><i style={{background:a.color}}/><strong>{a.name}</strong><small>{a.minutes} min</small><ChevronDown size={18}/></span><span className={service===a.name?'booking-description':'booking-description collapsed'}>{a.description}</span>{service===a.name&&<span className="booking-type-meta"><Clock size={15}/>{a.minutes} minutes <MapPin size={15}/>{a.location}</span>}</button>)}</div><Button className="booking-continue" onClick={next}>Continue <ChevronRight size={17}/></Button></>:<><h2>Select a date &amp; time</h2><p>Choose a preferred time in America/Phoenix. Working hours, buffers and existing bookings are not connected yet; the team must confirm your request.</p><section className="booking-calendar"><div className="booking-month"><button aria-label="Previous month" disabled={month<=today.slice(0,7)} onClick={()=>move(-1)}><ChevronLeft/></button><strong>{first.toLocaleDateString('en-US',{month:'long',year:'numeric',timeZone:'UTC'})}</strong><button aria-label="Next month" onClick={()=>move(1)}><ChevronRight/></button></div><div className="booking-days">{['SU','MO','TU','WE','TH','FR','SA'].map(d=><small key={d}>{d}</small>)}{Array.from({length:first.getUTCDay()},(_,i)=><span key={`blank${i}`}/>)}{Array.from({length:days},(_,i)=>{const value=`${month}-${String(i+1).padStart(2,'0')}`;return <button key={value} aria-label={value} aria-pressed={date===value} disabled={value<today} onClick={()=>{setDate(value);setTime('');}}>{i+1}</button>;})}</div><button className="booking-today" onClick={()=>{setMonth(today.slice(0,7));setDate(today);setTime('');}}>Today</button></section>{date&&<section className="booking-times"><h3>{new Date(`${date}T12:00:00-07:00`).toLocaleDateString('en-US',{weekday:'long',month:'long',day:'numeric',timeZone:'America/Phoenix'})}</h3><p>Preferred start time · Arizona time · {selected.minutes} minutes</p><div>{Array.from({length:29},(_,i)=>{const minutes=9*60+i*15,value=`${String(Math.floor(minutes/60)).padStart(2,'0')}:${String(minutes%60).padStart(2,'0')}`;const label=`${Math.floor(minutes/60)%12||12}:${String(minutes%60).padStart(2,'0')} ${minutes>=720?'PM':'AM'}`;return <button key={value} aria-pressed={time===value} disabled={new Date(`${date}T${value}:00-07:00`).getTime()<Date.now()} onClick={()=>setTime(value)}>{label}</button>;})}</div></section>}<div className="lfx-request-actions"><Button variant="outline" onClick={back}><ChevronLeft size={17}/>Back</Button><Button className="booking-continue" disabled={!date||!time} onClick={next}>Continue <ChevronRight size={17}/></Button></div></>;
}
