"use client";
import {useState} from 'react';
import Link from 'next/link';
import {Upload,Send,Check,X} from 'lucide-react';
import {Button} from './ui/button';
import {EstimateSelect} from './ui/estimate-controls';
import {Root as Toggle} from '@radix-ui/react-toggle';
const smsCopy='I agree to receive recurring automated SMS from LayeredFX about project updates, appointments, design news and offers. Message frequency varies. Message and data rates may apply. Consent is not a condition of purchase. Reply STOP to opt out or HELP for help.';
export function ContactForm({kind='contact'}:{kind?:'contact'|'opt-in'|'opt-out'}){
 const [files,setFiles]=useState<File[]>([]),[service,setService]=useState('Project quote'),[sms,setSms]=useState(false),[emailUpdates,setEmailUpdates]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[receipt,setReceipt]=useState(''),[requestId,setRequestId]=useState('');
 function addFiles(incoming:File[]){if([...files,...incoming].length>3||incoming.some(f=>f.size>2*1024*1024||!['image/jpeg','image/png','image/webp','application/pdf'].includes(f.type))){setError('Choose up to three JPEG, PNG, WebP or PDF files, 2 MB each.');return;}setFiles([...files,...incoming]);setError('');}
 async function submit(form:HTMLFormElement){setBusy(true);setError('');const data=new FormData(form),id=requestId||crypto.randomUUID();setRequestId(id);try{const attachments=await Promise.all(files.map(file=>new Promise<{name:string;type:string;data:string}>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve({name:file.name,type:file.type,data:String(reader.result).split(',')[1]});reader.onerror=()=>reject(Error('Could not read a file.'));reader.readAsDataURL(file);})));const response=await fetch('/api/contact',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,kind,name:[data.get('firstName'),data.get('lastName')].filter(Boolean).join(' '),email:data.get('email'),phone:data.get('phone'),company:data.get('company'),service,message:data.get('message'),website:data.get('website'),sms,emailUpdates,files:attachments})});const result=await response.json();if(!response.ok)throw Error(result.message||'Could not save. Please try again.');setReceipt(result.id);}catch(e){setError(e instanceof Error?e.message:'Could not submit.');}finally{setBusy(false);}}
 if(receipt)return <section className="lfx-contact-card" role="status"><Check/><h2>{kind==='contact'?'Your message is in.':'Your preferences are recorded.'}</h2><p>{kind==='contact'?'Thank you for sharing your project. Our team can review your message and attachments.':'We have recorded your selected channels. For SMS, you can also reply STOP directly to a LayeredFX message.'}</p><small>Reference: {receipt}</small><p><Link href="/contact">Contact the team</Link></p></section>;
 return <form className="lfx-contact-card lfx-contact-form" onSubmit={e=>{e.preventDefault();void submit(e.currentTarget);}}><h2>{kind==='contact'?'Send us a message':kind==='opt-in'?'Choose your updates':'Choose what to stop'}</h2><p>{kind==='contact'?'Tell us about your surfaces, plans, and ideas.':'Select SMS, email, or both. Your choices are independent.'}</p><div className="lfx-contact-pair"><label>First name{kind==='contact'?' *':''}<input name="firstName" required={kind==='contact'} autoComplete="given-name" maxLength={75}/></label><label>Last name<input name="lastName" autoComplete="family-name" maxLength={75}/></label></div><label>Email{kind==='contact'||emailUpdates?' *':''}<input name="email" type="email" required={kind==='contact'||emailUpdates} autoComplete="email" maxLength={200} placeholder="you@company.com"/></label><label>Phone{sms?' *':' (optional)'}<input name="phone" type="tel" required={sms} autoComplete="tel" maxLength={40} placeholder="(480) 555-0123"/></label>{kind==='contact'&&<><label>Company (optional)<input name="company" autoComplete="organization" maxLength={200}/></label><label>What can we help with?<EstimateSelect label="Project interest" value={service} onChange={setService} options={['Project quote','Wall wraps','Wallpaper','Wall cladding','Window film','Roman clay','Design services','Existing project']}/></label><label>Tell us more *<textarea name="message" required rows={5} maxLength={5000} placeholder="Surfaces, approximate size, timeline, and the look you have in mind..."/></label><div className="lfx-file-drop" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();addFiles(Array.from(e.dataTransfer.files));}}><Upload/><label>Drop files or browse<input type="file" multiple accept="image/jpeg,image/png,image/webp,application/pdf" onChange={e=>{addFiles(Array.from(e.target.files||[]));e.target.value='';}}/></label><small>Photos, references or plans. Up to 3 files, 2 MB each.</small></div>{files.map((file,i)=><div className="lfx-file-row" key={i}><span>{file.name}</span><button type="button" aria-label={`Remove ${file.name}`} onClick={()=>setFiles(files.filter((_,index)=>index!==i))}><X size={16}/></button></div>)}</>}
 <fieldset><legend>{kind==='contact'?'Optional updates':kind==='opt-in'?'Opt in to':'Opt out of'}</legend><div className="lfx-consent-option"><Toggle aria-label={kind==='opt-out'?'Stop SMS':'SMS consent'} pressed={sms} onPressedChange={setSms}><Check size={16}/></Toggle><span>{kind==='opt-out'?'Stop SMS updates and promotions.':smsCopy}</span></div><div className="lfx-consent-option"><Toggle aria-label={kind==='opt-out'?'Stop email':'Email consent'} pressed={emailUpdates} onPressedChange={setEmailUpdates}><Check size={16}/></Toggle><span>{kind==='opt-out'?'Stop marketing emails. Essential project or account messages may still be sent.':'I agree to receive LayeredFX design news and offers by email. I can unsubscribe at any time.'}</span></div></fieldset><div hidden aria-hidden="true"><label>Website<input name="website" tabIndex={-1} autoComplete="off"/></label></div>{error&&<p role="alert">{error}</p>}<Button type="submit" disabled={busy}>{busy?'Saving...':kind==='contact'?'Send message':kind==='opt-in'?'Save opt-in preferences':'Save opt-out preferences'}<Send size={16}/></Button><small>Read our <Link href="/privacy">Privacy Policy</Link> and <Link href="/terms">Terms of Service</Link>. Contacting us does not require marketing consent.</small></form>;
}
