"use client";
import Link from 'next/link';
import {useState} from 'react';
import {ArrowUpRight, CalendarDays, MessageCircle, Layers3} from 'lucide-react';
import {BookingChoices} from './booking-choices';
import '@/components/admin/dashboard.css';
import {Header} from './header';
import {EstimateProvider} from './estimate-context';
import {Button} from './ui/button';

export function PublicRequest({booking=false}:{booking?:boolean}) {
 const [details,setDetails]=useState<Record<string,string>>({});
 const [step,setStep]=useState(1),[service,setService]=useState('Surface consultation'),[date,setDate]=useState(''),[period,setPeriod]=useState(''),[error,setError]=useState('');
 function continueRequest(form:HTMLFormElement){
  const data=new FormData(form);
  const body=[`Name: ${data.get('name')||[data.get('firstName'),data.get('lastName')].filter(Boolean).join(' ')}`,`Email: ${data.get('email')}`,`Phone: ${data.get('phone')||'Not provided'}`,`Company: ${data.get('company')||'Not provided'}`,booking?`Preferred time: ${period} (America/Phoenix). Subject to confirmation.`:'',String(data.get('message'))].filter(Boolean).join('\n');
  try{sessionStorage.setItem('lfx:public-draft',JSON.stringify({kind:booking?'booking':'message',title:booking?service:'Project inquiry',body,date:booking?date:''}));location.assign(booking?'/portal/bookings':'/portal/messages');}catch{setError('Your browser could not save the draft. Please enable session storage or open your account to contact the team.');}
 }
 return <EstimateProvider><div className={`lfx lfx-public ${booking?'lfx-booking-page':''}`}><Header/><main id="main"><section className="lfx-public-heading"><span className="lfx-eyebrow">LAYEREDFX / {booking?'PLAN YOUR NEXT STEP':'LET’S CONNECT'}</span><h1>{booking?'A new layer starts here.':'Let’s talk about your space.'}</h1><p>{booking?'Choose a consultation, tell us your preferred date, and share a few project details.':'Quotes, materials, installation and the possibilities for your next project.'}</p></section><div className="lfx-public-grid lfx-container"><section className="lfx-request-card">
 {booking&&<ol className="lfx-booking-steps">{['Choose type','Date & time','Your details'].map((label,i)=><li key={label} aria-current={step===i+1?'step':undefined}><span>{step>i+1?'Done':i+1}</span>{label}</li>)}</ol>}
 {booking&&step<3?<BookingChoices step={step} service={service} setService={setService} date={date} setDate={setDate} time={period} setTime={setPeriod} next={()=>setStep(step+1)} back={()=>setStep(step-1)}/>:<form onSubmit={e=>{e.preventDefault();continueRequest(e.currentTarget);}}><h2>{booking?'Your details':'Send a project inquiry'}</h2>{booking&&<p>{service} · {date} · {period} <button type="button" className="lfx-edit-date" onClick={()=>setStep(2)}>Edit</button></p>}{booking?<div className="lfx-request-pair"><label>First name<input name="firstName" value={details.firstName||''} onChange={e=>setDetails(d=>({...d,firstName:e.target.value}))} required autoComplete="given-name" maxLength={75}/></label><label>Last name<input name="lastName" value={details.lastName||''} onChange={e=>setDetails(d=>({...d,lastName:e.target.value}))} required autoComplete="family-name" maxLength={75}/></label></div>:<label>Name<input name="name" value={details.name||''} onChange={e=>setDetails(d=>({...d,name:e.target.value}))} required autoComplete="name" maxLength={150}/></label>}<label>Email<input name="email" value={details.email||''} onChange={e=>setDetails(d=>({...d,email:e.target.value}))} type="email" required autoComplete="email" maxLength={200}/></label><div className="lfx-request-pair"><label>Phone (optional)<input name="phone" value={details.phone||''} onChange={e=>setDetails(d=>({...d,phone:e.target.value}))} type="tel" autoComplete="tel" maxLength={40}/></label><label>Company (optional)<input name="company" value={details.company||''} onChange={e=>setDetails(d=>({...d,company:e.target.value}))} autoComplete="organization" maxLength={200}/></label></div><label>Tell us more<textarea name="message" value={details.message||''} onChange={e=>setDetails(d=>({...d,message:e.target.value}))} required rows={5} maxLength={3000} placeholder="Your surfaces, measurements, timeline and what you have in mind…"/></label><p>You’ll review and submit this {booking?'request':'message'} in your account. Sign in or register if needed. Photos and videos can be added in your portal.</p>{error&&<p role="alert">{error}</p>}{booking&&<Button variant="outline" onClick={()=>setStep(2)}>Back</Button>}<Button type="submit">Continue to my account <ArrowUpRight size={17}/></Button></form>}
 </section><aside><div className="lfx-public-art"><Layers3 size={74}/><span>YOUR SPACE. A NEW POSSIBILITY.</span></div><section className="lfx-request-card"><h2>Thoughtful from the first conversation.</h2><p>For homes and businesses, from a single surface to a complete transformation.</p><Link href="/book"><CalendarDays size={21}/><span>Plan a consultation<small>Share your preferred date and project goals.</small></span><ArrowUpRight size={17}/></Link><Link href="/portal/messages"><MessageCircle size={21}/><span>Already working with us?<small>Keep the conversation in your account.</small></span><ArrowUpRight size={17}/></Link><Link href="/#services">Explore our services <ArrowUpRight size={17}/></Link></section></aside></div></main><footer className="lfx-public-footer lfx-container"><span>LayeredFX · Residential & commercial</span><Link href="/contact">Contact</Link><Link href="/book">Book a consultation</Link><Link href="/login">My Account</Link></footer></div></EstimateProvider>;
}
