"use client";
import Link from 'next/link';
import {useState} from 'react';
import {ArrowUpRight, CalendarDays, MessageCircle, Layers3} from 'lucide-react';
import {BrandedInput} from '@/components/operations/branded-fields';
import '@/components/admin/dashboard.css';
import {Header} from './header';
import {EstimateProvider} from './estimate-context';
import {Button} from './ui/button';

export function PublicRequest({booking=false}:{booking?:boolean}) {
 const [step,setStep]=useState(1),[service,setService]=useState('Surface consultation'),[date,setDate]=useState(''),[period,setPeriod]=useState('Flexible'),[error,setError]=useState('');
 function continueRequest(form:HTMLFormElement){
  const data=new FormData(form);
  const body=[`Name: ${data.get('name')}`,`Email: ${data.get('email')}`,`Phone: ${data.get('phone')||'Not provided'}`,`Company: ${data.get('company')||'Not provided'}`,booking?`Preferred time: ${period} (America/Phoenix). Subject to confirmation.`:'',String(data.get('message'))].filter(Boolean).join('\n');
  try{sessionStorage.setItem('lfx:public-draft',JSON.stringify({kind:booking?'booking':'message',title:booking?service:'Project inquiry',body,date:booking?date:''}));location.assign(booking?'/portal/bookings':'/portal/messages');}catch{setError('Your browser could not save the draft. Please enable session storage or open your account to contact the team.');}
 }
 return <EstimateProvider><div className="lfx lfx-public"><Header/><main id="main"><section className="lfx-public-heading"><span className="lfx-eyebrow">LAYEREDFX / {booking?'PLAN YOUR NEXT STEP':'LET’S CONNECT'}</span><h1>{booking?'A new layer starts here.':'Let’s talk about your space.'}</h1><p>{booking?'Choose a consultation, tell us your preferred date, and share a few project details.':'Quotes, materials, installation and the possibilities for your next project.'}</p></section><div className="lfx-public-grid lfx-container"><section className="lfx-request-card">
 {booking&&<ol className="lfx-booking-steps">{['Consultation','Preferred date','Your details'].map((label,i)=><li key={label} aria-current={step===i+1?'step':undefined}>{i+1}. {label}</li>)}</ol>}
 {booking&&step===1?<><h2>What are you planning?</h2><div className="lfx-booking-services">{['Surface consultation','Material & design consultation','Installation consultation'].map(label=><button key={label} aria-pressed={service===label} onClick={()=>setService(label)}><Layers3 size={22}/><span>{label}</span></button>)}</div><Button onClick={()=>setStep(2)}>Choose a preferred date <ArrowUpRight size={17}/></Button></>:booking&&step===2?<form onSubmit={e=>{e.preventDefault();setStep(3);}}><h2>When works for you?</h2><p>This is a preferred date, not a reserved appointment. The team will confirm availability.</p><label>Preferred date<BrandedInput type="date" required value={date} min={new Intl.DateTimeFormat('en-CA',{timeZone:'America/Phoenix'}).format(new Date())} onChange={e=>setDate(e.target.value)}/></label><fieldset><legend>Preferred time · Arizona time</legend><div className="lfx-time-options">{['Morning','Afternoon','Flexible'].map(value=><button type="button" key={value} aria-pressed={period===value} onClick={()=>setPeriod(value)}>{value}</button>)}</div></fieldset><div className="lfx-request-actions"><Button type="button" variant="outline" onClick={()=>setStep(1)}>Back</Button><Button type="submit">Continue <ArrowUpRight size={17}/></Button></div></form>:<form onSubmit={e=>{e.preventDefault();continueRequest(e.currentTarget);}}><h2>{booking?'Tell us about your project':'Send a project inquiry'}</h2>{booking&&<p>{service} · {date} · {period} <button type="button" className="lfx-edit-date" onClick={()=>setStep(2)}>Edit</button></p>}<label>Name<input name="name" required autoComplete="name" maxLength={150}/></label><label>Email<input name="email" type="email" required autoComplete="email" maxLength={200}/></label><div className="lfx-request-pair"><label>Phone (optional)<input name="phone" type="tel" autoComplete="tel" maxLength={40}/></label><label>Company (optional)<input name="company" autoComplete="organization" maxLength={200}/></label></div><label>Tell us more<textarea name="message" required rows={5} maxLength={3000} placeholder="Your surfaces, measurements, timeline and what you have in mind…"/></label><p>You’ll review and submit this {booking?'request':'message'} in your account. Sign in or register if needed. Photos and videos can be added in your portal.</p>{error&&<p role="alert">{error}</p>}<Button type="submit">Continue to my account <ArrowUpRight size={17}/></Button></form>}
 </section><aside><div className="lfx-public-art"><Layers3 size={74}/><span>YOUR SPACE. A NEW POSSIBILITY.</span></div><section className="lfx-request-card"><h2>Thoughtful from the first conversation.</h2><p>For homes and businesses, from a single surface to a complete transformation.</p><Link href="/book"><CalendarDays size={21}/><span>Plan a consultation<small>Share your preferred date and project goals.</small></span><ArrowUpRight size={17}/></Link><Link href="/portal/messages"><MessageCircle size={21}/><span>Already working with us?<small>Keep the conversation in your account.</small></span><ArrowUpRight size={17}/></Link><Link href="/#services">Explore our services <ArrowUpRight size={17}/></Link></section></aside></div></main><footer className="lfx-public-footer lfx-container"><span>LayeredFX · Residential & commercial</span><Link href="/contact">Contact</Link><Link href="/book">Book a consultation</Link><Link href="/login">My Account</Link></footer></div></EstimateProvider>;
}
