'use client';
import {useState} from 'react';
import {estimate,type WallMeasure} from '@/lib/studio/estimate';
export function StudioEstimate({materialName}:{materialName:string}){
 const [walls,setWalls]=useState<WallMeasure[]>([{name:'Wall 1',width:0,height:0,openings:0}]),[waste,setWaste]=useState(10),[rate,setRate]=useState(''),[labor,setLabor]=useState('');
 const result=estimate(walls,waste,Number(rate),Number(labor)),money=(v:number)=>v.toLocaleString('en-US',{style:'currency',currency:'USD'});
 const update=(i:number,key:keyof WallMeasure,value:string)=>setWalls(rows=>rows.map((w,j)=>i===j?{...w,[key]:key==='name'?value:Math.max(0,Number(value))}:w));
 function download(){const blob=new Blob([JSON.stringify({material:materialName,walls,unit:'feet',wastePercent:waste,materialRate:rate||null,installationRate:labor||null,...result,estimateOnly:true,excludes:'Taxes, preparation, shipping, minimums and site-specific work'},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='LayeredFX-planning-estimate.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 return <section className="ws-estimator"><div><span className="lfx-eyebrow">PLAN YOUR PROJECT</span><h2>Measure. Allow. Estimate.</h2><p>Enter measured dimensions in feet. Foreground furniture does not reduce the wall area; deduct only openings that will not receive material.</p></div>{walls.map((w,i)=><fieldset key={i}><legend>{w.name||`Wall ${i+1}`}</legend><label>Wall name<input value={w.name} onChange={e=>update(i,'name',e.target.value)}/></label>{(['width','height','openings'] as const).map(key=><label key={key}>{key==='openings'?'Openings (sq ft)':`${key==='width'?'Width':'Height'} (ft)`}<input type="number" min="0" max="100000" step=".1" value={w[key]||''} onChange={e=>update(i,key,e.target.value)}/></label>)}{walls.length>1&&<button onClick={()=>setWalls(rows=>rows.filter((_,j)=>i!==j))}>Remove wall</button>}</fieldset>)}<button disabled={walls.length>=20} onClick={()=>setWalls(rows=>[...rows,{name:`Wall ${rows.length+1}`,width:0,height:0,openings:0}])}>Add another wall</button><div className="ws-estimate-rates"><label>Waste allowance (%)<input type="number" min="0" max="100" value={waste} onChange={e=>setWaste(Math.min(100,Math.max(0,+e.target.value)))}/></label><label>Material ($ / sq ft)<input type="number" min="0" step=".01" placeholder="Enter your rate" value={rate} onChange={e=>setRate(e.target.value)}/></label><label>Installation ($ / sq ft)<input type="number" min="0" step=".01" placeholder="Enter your rate" value={labor} onChange={e=>setLabor(e.target.value)}/></label></div><div className="ws-estimate-summary"><span>Net surface <strong>{result.area.toFixed(1)} sq ft</strong></span><span>Material allowance <strong>{result.orderArea.toFixed(1)} sq ft</strong></span><span>Planning total <strong>{rate!==''&&labor!==''?money(result.total):'Add rates'}</strong></span></div><p>Material: {materialName}. Planning estimate only; excludes preparation, taxes, shipping and minimum charges. Sheet sizes and pattern repeats may increase required quantities.</p><button onClick={download} disabled={!result.area}>Download measurements & estimate</button><a href="/book">Review with us in a consultation ↗</a></section>;
}
