"use client";
import {useEffect,useMemo,useRef,useState,type PointerEvent} from 'react';
import Link from 'next/link';
import {Camera,Upload,Download,Undo2,Redo2,Layers3} from 'lucide-react';
import {Header} from './header';
import {EstimateProvider} from './estimate-context';
import {Button} from './ui/button';
import {DEMO_ROOM_SVG} from '@/lib/studio/demo';
import {defaultCorners,finishes,renderStudio,surface,validQuad,type Mask} from '@/lib/studio/render';
import type {Point} from '@/lib/studio/homography';
import {localMedia} from '@/lib/portal/local-media';
import './studio.css';
import vendorMaterials from '@/lib/studio/wilsonart.json';
import {StudioEstimate} from './studio-estimate';

const demo='data:image/svg+xml;charset=utf-8,'+encodeURIComponent(DEMO_ROOM_SVG);
function load(src:string){return new Promise<HTMLImageElement>((resolve,reject)=>{const img=new Image();img.onload=()=>resolve(img);img.onerror=()=>reject(Error('This image could not be opened. Choose JPEG, PNG or WebP.'));img.src=src;});}
export function WallStudio(){
 const [photo,setPhoto]=useState<HTMLImageElement|null>(null),[photoSrc,setPhotoSrc]=useState(demo),[art,setArt]=useState<HTMLImageElement|null>(null),[artSrc,setArtSrc]=useState(''),[corners,setCorners]=useState(defaultCorners),[finish,setFinish]=useState('palm'),[scale,setScale]=useState(150),[opacity,setOpacity]=useState(.85),[mode,setMode]=useState('wall'),[radius,setRadius]=useState(24),[masks,setMasks]=useState<Mask[]>([]),[redo,setRedo]=useState<Mask[]>([]),[polygon,setPolygon]=useState<Point[]>([]),[before,setBefore]=useState(false),[showMask,setShowMask]=useState(false),[message,setMessage]=useState('Sample room. Add a photo of your own space to begin.'),[busy,setBusy]=useState(false),[category,setCategory]=useState('All'),[vendorName,setVendorName]=useState(''),[materialQuery,setMaterialQuery]=useState(''),[pending,setPending]=useState<Mask|null>(null),[zoom,setZoom]=useState(1),[rotation,setRotation]=useState(0);
 const worker=useRef<Worker|null>(null);
 useEffect(()=>()=>worker.current?.terminate(),[]);
 const canvas=useRef<HTMLCanvasElement>(null),stroke=useRef<Mask|null>(null),file=useRef<HTMLInputElement>(null),camera=useRef<HTMLInputElement>(null),graphic=useRef<HTMLInputElement>(null);
 useEffect(()=>{let active=true;load(photoSrc).then(img=>{if(active)setPhoto(img);}).catch(e=>setMessage(e.message));return()=>{active=false;};},[photoSrc]);
 useEffect(()=>{let active=true;if(!artSrc){setArt(null);return;}load(artSrc).then(img=>{if(active)setArt(img);}).catch(e=>setMessage(e.message));return()=>{active=false;};},[artSrc]);
 const texture=useMemo(()=>typeof document==='undefined'?null:surface(finish,scale,art,rotation,!!vendorName),[finish,scale,art,rotation,vendorName]);
 useEffect(()=>{if(canvas.current&&photo)renderStudio(canvas.current,photo,corners,texture,pending?[...masks,pending]:masks,opacity,before,showMask);},[photo,corners,texture,masks,opacity,before,showMask,pending]);
 function autoSelect(p:Point){if(busy)return;setBusy(true);setPending(null);setShowMask(true);if(!worker.current){worker.current=new Worker(new URL('../../lib/studio/segment.worker.ts',import.meta.url));worker.current.onmessage=e=>{if(e.data.status){setMessage(e.data.status);return;}setBusy(false);if(e.data.error){setMessage(e.data.error);return;}setPending({points:[],polygon:false,radius:0,restore:false,label:'Selected object',...e.data});setMessage('Review the highlighted selection, then keep it in front. Use the brush to refine edges.');};worker.current.onerror=()=>{setBusy(false);setMessage('Automatic selection is unavailable. Use the outline or brush tools.');worker.current?.terminate();worker.current=null;};}if(!photo){setBusy(false);return;}const original=document.createElement('canvas');original.width=photo.width;original.height=photo.height;original.getContext('2d')!.drawImage(photo,0,0);worker.current.postMessage({src:original.toDataURL('image/png'),x:p.x,y:p.y});}
 function cancelSelection(){worker.current?.terminate();worker.current=null;setBusy(false);setPending(null);setMessage('Selection cancelled.');}
 function addMask(mask:Mask){if(masks.length>=200){setMessage('This look has reached 200 mask edits. Undo an edit before adding another.');if(canvas.current&&photo)renderStudio(canvas.current,photo,corners,texture,masks,opacity,false,showMask);return;}setMasks(old=>[...old,mask]);setRedo([]);}
 function point(e:PointerEvent<HTMLElement>):Point{const r=canvas.current!.getBoundingClientRect();return{x:Math.max(0,Math.min(1,(e.clientX-r.left)/r.width)),y:Math.max(0,Math.min(1,(e.clientY-r.top)/r.height))};}
 function paint(e:PointerEvent<HTMLCanvasElement>){if(!stroke.current||!photo||!canvas.current)return;const p=point(e),last=stroke.current.points.at(-1)!;if(Math.hypot(p.x-last.x,p.y-last.y)>.002&&stroke.current.points.length<3000)stroke.current.points.push(p);renderStudio(canvas.current,photo,corners,texture,[...masks,stroke.current],opacity,false,showMask);}
 async function upload(selected:File|undefined,isArt=false){if(!selected)return;worker.current?.terminate();worker.current=null;setPending(null);setBusy(true);try{if(!['image/jpeg','image/png','image/webp'].includes(selected.type)||selected.size>24*1024*1024)throw Error('Choose a JPEG, PNG or WebP image under 24 MB.');const url=URL.createObjectURL(selected);let img:HTMLImageElement;try{img=await load(url);}finally{URL.revokeObjectURL(url);}const c=document.createElement('canvas');const ratio=Math.min(1,1600/Math.max(img.width,img.height));c.width=Math.round(img.width*ratio);c.height=Math.round(img.height*ratio);c.getContext('2d')!.drawImage(img,0,0,c.width,c.height);const src=c.toDataURL('image/png');if(isArt){setArtSrc(src);setFinish('custom');setVendorName('');setMessage('Your graphic is applied. Fit the wall corners, then keep foreground objects visible.');}else{setPhotoSrc(src);setCorners(defaultCorners);setMasks([]);setRedo([]);setPolygon([]);setMessage('Photo ready. Drag the four corners to outline the wall.');}}catch(e){setMessage(e instanceof Error?e.message:'Could not load the image.');}finally{setBusy(false);}}
 async function save(){setBusy(true);try{await localMedia('lfx-wall-studio-project',new Blob([JSON.stringify({photoSrc,artSrc,corners,finish,scale,opacity,masks,vendorName,rotation})],{type:'application/json'}));setMessage('Look saved on this device, including your photo and foreground masks.');}catch{setMessage('Could not save. Download a preview to keep your work.');}finally{setBusy(false);}}
 async function restore(){setPending(null);setBusy(true);try{const blob=await localMedia('lfx-wall-studio-project');if(!blob)throw Error('No saved look on this device yet.');const data=JSON.parse(await blob.text());if(!Array.isArray(data.corners)||data.corners.length!==4||!validQuad(data.corners)||!Array.isArray(data.masks))throw Error('Saved look could not be restored.');setPhotoSrc(data.photoSrc);setArtSrc(data.artSrc);setCorners(data.corners);setFinish(data.finish);setVendorName(data.vendorName||'');setRotation(data.rotation||0);setScale(data.scale);setOpacity(data.opacity);setMasks(data.masks);setRedo([]);setPolygon([]);setMessage('Saved look restored.');}catch(e){setMessage(e instanceof Error?e.message:'Could not restore.');}finally{setBusy(false);}}
 function download(){if(!canvas.current||!photo)return;const output=document.createElement('canvas');output.width=canvas.current.width;output.height=canvas.current.height;renderStudio(output,photo,corners,texture,masks,opacity,false);output.toBlob(blob=>{if(!blob){setMessage('Preview export failed.');return;}const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='LayeredFX-wall-preview.png';a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);},'image/png');}
 const selected=finishes.find(f=>f.id===finish);
 const materialName=vendorName||selected?.name||'Your graphic';
 async function chooseVendor(item:typeof vendorMaterials[number]){setBusy(true);try{await load(item.image);setArtSrc(item.image);setFinish('custom');setVendorName('Wilsonart '+item.name);setMessage('Wilsonart swatch applied. Confirm color and suitability with a physical sample.');}catch{setMessage('The material image could not be loaded. Please try again.');}finally{setBusy(false);}}
 return <EstimateProvider><div className="lfx lfx-wall-studio"><Header/><main className="lfx-container"><section className="ws-heading"><div><span className="lfx-eyebrow">WALL STUDIO</span><h1>See the finish.<br/><em>Keep your space.</em></h1><p>Wallpaper, graphics, Roman clay and architectural finishes, previewed on your own wall. Keep furniture and plants naturally in front.</p></div><div className="ws-start"><Button onClick={()=>camera.current?.click()} disabled={busy}><Camera size={18}/>Take a photo</Button><Button variant="outline" onClick={()=>file.current?.click()} disabled={busy}><Upload size={18}/>Upload your space</Button><Button variant="ghost" onClick={restore} disabled={busy}>Open saved look</Button></div></section>
 <input ref={file} hidden type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>{void upload(e.target.files?.[0]);e.target.value='';}}/><input ref={camera} hidden type="file" accept="image/*" capture="environment" onChange={e=>{void upload(e.target.files?.[0]);e.target.value='';}}/><input ref={graphic} hidden type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>{void upload(e.target.files?.[0],true);e.target.value='';}}/>
 <ol className="ws-workflow"><li>1. Add your photo</li><li>2. Fit the wall</li><li>3. Choose a finish</li><li>4. Keep objects in front</li></ol>
 <div className="ws-workbench"><section className="ws-preview"><div className="ws-toolbar"><button aria-pressed={before} onClick={()=>setBefore(!before)}>{before?'Show design':'Show original'}</button><span>{materialName}</span><button aria-pressed={showMask} onClick={()=>setShowMask(!showMask)}>Show foreground mask</button></div><div className="ws-viewport"><div className="ws-canvas" style={{width:`${zoom*100}%`,aspectRatio:photo?`${photo.width}/${photo.height}`:'4/3'}}>
 <canvas ref={canvas} width={photo?.width||1200} height={photo?.height||900} aria-label="Wall preview. Use corner controls to fit the wall, or paint to keep objects in front." onPointerDown={e=>{if(before||busy||mode==='wall')return;if(mode==='auto'){autoSelect(point(e));return;}if(mode==='polygon'){setPolygon(p=>[...p,point(e)].slice(0,100));return;}e.currentTarget.setPointerCapture(e.pointerId);stroke.current={points:[point(e)],radius:radius/(canvas.current?.getBoundingClientRect().width||800),polygon:false,restore:mode==='restore'};paint(e);}} onPointerMove={paint} onPointerUp={()=>{if(stroke.current){addMask(stroke.current);stroke.current=null;}}} onPointerCancel={()=>{if(stroke.current){addMask(stroke.current);stroke.current=null;}}}/>
 {!before&&mode==='wall'&&corners.map((p,i)=><button key={i} className="ws-corner" aria-label={`Wall corner ${['top left','top right','bottom left','bottom right'][i]}`} style={{left:`${p.x*100}%`,top:`${p.y*100}%`}} onPointerDown={e=>e.currentTarget.setPointerCapture(e.pointerId)} onPointerMove={e=>{if(!e.currentTarget.hasPointerCapture(e.pointerId))return;const next=corners.map((v,j)=>j===i?point(e):v);if(validQuad(next))setCorners(next);}} onKeyDown={e=>{const move:{[key:string]:number[]}={ArrowLeft:[-.005,0],ArrowRight:[.005,0],ArrowUp:[0,-.005],ArrowDown:[0,.005]};if(!move[e.key])return;e.preventDefault();const delta=move[e.key],next=corners.map((v,j)=>j===i?{x:Math.max(0,Math.min(1,v.x+delta[0])),y:Math.max(0,Math.min(1,v.y+delta[1]))}:v);if(validQuad(next))setCorners(next);}}>{i+1}</button>)}
 {!!polygon.length&&<svg className="ws-polygon" viewBox="0 0 100 100" preserveAspectRatio="none"><polyline points={polygon.map(p=>`${p.x*100},${p.y*100}`).join(' ')} fill="#d6ff4133" stroke="#d6ff41" strokeWidth=".3"/>{polygon.map((p,i)=><circle key={i} cx={p.x*100} cy={p.y*100} r=".6" fill="#d6ff41"/>)}</svg>}
 </div></div><label className="ws-zoom">Zoom <input type="range" min="1" max="3" step=".1" value={zoom} onChange={e=>setZoom(+e.target.value)}/><button onClick={()=>setZoom(1)}>Fit view</button></label><p role="status" className="ws-status">{message}</p><p className="ws-note">{mode==='wall'?'Drag the numbered corners to the wall edges. Arrow keys fine-tune a focused corner.':mode==='polygon'?'Tap around the object, then choose Keep outlined object.':'Paint over the object to reveal the original photo in front of the finish.'} Your original photo stays untouched.</p></section>
 <aside className="ws-controls"><h2>Preview controls</h2><div className="ws-tools" role="group" aria-label="Wall tools">{[['wall','Fit wall'],['auto','Auto-select object'],['brush','Keep objects in front'],['polygon','Outline an object'],['restore','Restore finish']].map(([id,label])=><button key={id} aria-pressed={mode===id} onClick={()=>{setMode(id);setBefore(false);setPolygon([]);}}>{label}</button>)}</div>
 {mode==='auto'&&<p className="ws-note">Tap the couch, plant or other object. Selection tools download on first use; the photo is processed on your device.</p>}{busy&&<button onClick={cancelSelection}>Cancel selection</button>}{pending&&<div className="ws-actions"><Button onClick={()=>{addMask(pending);setPending(null);setShowMask(false);setMessage('Object kept in front. Change finishes or refine its edges with the brush.');}}>Keep selected object in front</Button><button onClick={()=>setPending(null)}>Discard selection</button></div>}{mode==='polygon'&&<div className="ws-actions"><Button disabled={polygon.length<3} onClick={()=>{addMask({points:polygon,polygon:true,radius:0,restore:false});setPolygon([]);}}>Keep outlined object</Button><button onClick={()=>setPolygon([])}>Cancel outline</button></div>}
 {['brush','restore'].includes(mode)&&<label>Brush size <input type="range" min="4" max="90" value={radius} onChange={e=>setRadius(+e.target.value)}/><small>{radius*2}px diameter</small></label>}
 <div className="ws-actions"><button disabled={!masks.length} onClick={()=>{setRedo(r=>[...r,masks[masks.length-1]]);setMasks(m=>m.slice(0,-1));}}><Undo2 size={17}/>Undo mask</button><button disabled={!redo.length} onClick={()=>{setMasks(m=>[...m,redo[redo.length-1]]);setRedo(r=>r.slice(0,-1));}}><Redo2 size={17}/>Redo</button></div>
 <label>Pattern scale<input type="range" min="60" max="350" value={scale} disabled={finish==='custom'&&!vendorName} onChange={e=>setScale(+e.target.value)}/></label>{finish==='custom'&&<label>Material rotation<input type="range" min="0" max="180" step="15" value={rotation} onChange={e=>setRotation(+e.target.value)}/><small>{rotation} degrees</small></label>}<label>Blend strength<input type="range" min="0" max="1" step=".01" value={opacity} onChange={e=>setOpacity(+e.target.value)}/></label>
 <Button variant="outline" onClick={()=>graphic.current?.click()}><Upload size={17}/>Add your graphic</Button><Button onClick={download} disabled={!photo}><Download size={17}/>Download preview</Button><Button variant="outline" onClick={save} disabled={busy}>Save this look</Button><button onClick={()=>setCorners(defaultCorners)}>Reset wall corners</button><Link href="/book">Discuss installation <Layers3 size={16}/></Link><p className="ws-note">Illustrative materials, not a color match or measured installation quote. Photos and saved looks stay on this device.</p></aside></div>
 <section className="ws-layers"><h2>Foreground layers</h2><p>Objects remain above every finish. Hide a layer to compare, or undo your latest mask edit.</p>{masks.map((m,i)=><label key={i}><input type="checkbox" checked={!m.hidden} onChange={()=>setMasks(rows=>rows.map((r,j)=>j===i?{...r,hidden:!r.hidden}:r))}/>{m.label||`${m.restore?'Edge correction':'Foreground mask'} ${i+1}`}</label>)}{!masks.length&&<p>Select an object or paint a foreground mask to add a layer.</p>}</section><StudioEstimate materialName={materialName}/><section className="ws-designs"><h2>Wilsonart material library</h2><p>Vendor swatches for visual exploration. HPL is a sheet material, not adhesive wallpaper; fabrication, substrate and installation suitability must be confirmed.</p><label>Find a material<input type="search" placeholder="Search Wilsonart materials" value={materialQuery} onChange={e=>setMaterialQuery(e.target.value)}/></label><div className="ws-vendor-grid">{vendorMaterials.filter(m=>m.name.toLowerCase().includes(materialQuery.toLowerCase())).map(m=><article key={m.id}><img src={m.image} alt={m.name}/><small>Wilsonart ? HPL woodgrain</small><h3>{m.name}</h3><button disabled={busy} onClick={()=>chooseVendor(m)}>Preview on my wall</button><a href={m.source} target="_blank" rel="noreferrer">Details & samples ?</a></article>)}</div><a href="https://www.wilsonart.com/wilsonartwoodgrains" target="_blank" rel="noreferrer">Explore the full Wilsonart collection ?</a></section><section className="ws-designs"><h2>Illustrative finishes</h2><p>Choose a finish; your wall placement and foreground objects stay in place.</p><div className="ws-categories">{['All',...new Set(finishes.map(f=>f.category))].map(c=><button key={c} aria-pressed={category===c} onClick={()=>setCategory(c)}>{c}</button>)}</div><div className="ws-design-row">{finishes.filter(f=>category==='All'||f.category===category).map(f=><button key={f.id} aria-pressed={finish===f.id} onClick={()=>{setFinish(f.id);setVendorName('');}}><span className={`ws-swatch ws-swatch-${f.id}`} style={{backgroundColor:f.color}}/><small>{f.category}</small><b>{f.name}</b><span>Preview this finish</span></button>)}</div></section></main></div></EstimateProvider>;
}
