import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import ts from 'typescript';
const dataUrl=code=>'data:text/javascript;base64,'+Buffer.from(code).toString('base64');
const transpile=(path,replacements={})=>{let out=ts.transpileModule(readFileSync(new URL(path,import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText;for(const [from,to] of Object.entries(replacements))out=out.replaceAll(from,to);return out;};
const engine=new URL('../lib/operations/engine.mjs',import.meta.url).href,security=new URL('../lib/operations/security.mjs',import.meta.url).href;
const catalog=dataUrl(transpile('../lib/bookings/catalog.ts'));
const modelUrl=dataUrl(transpile('../lib/bookings/model.ts',{"'@/lib/operations/engine.mjs'":`'${engine}'`,"'@/lib/bookings/catalog'":`'${catalog}'`}));
const model=await import(modelUrl);
const phoenixDay=days=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/Phoenix'}).format(new Date(Date.now()+days*86400000));
const input=(over={})=>({id:crypto.randomUUID(),appointment:'surface-consultation',date:phoenixDay(7),time:'09:30',firstName:' Ana ',lastName:'Ruiz',email:'Ana@Example.com',phone:'(480) 555-0100',company:'',message:'Kitchen cabinets',...over});
const statusOf=fn=>{try{fn();}catch(e){return e.status;}return 200;};

test('public booking stores a validated Arizona appointment window',()=>{const body=input(),b=model.newPublicBooking(body);assert.equal(b.customer_email,'ana@example.com');assert.equal(b.customer_first_name,'Ana');assert.equal(b.start_time,new Date(`${body.date}T09:30:00-07:00`).toISOString());assert.equal(Date.parse(b.end_time)-Date.parse(b.start_time),30*60000);assert.equal(b.status,'pending');assert.equal(b.revision,0);assert.equal(b.history.length,1);});
test('public booking rejects unknown types, closed hours, past, far-future and malformed details',()=>{for(const over of [{appointment:'free-install'},{time:'09:07'},{time:'16:15'},{time:'08:45'},{date:'2026-02-30'},{date:phoenixDay(-2)},{date:phoenixDay(200)},{firstName:''},{email:'not-an-email'},{id:'123'},{phone:'call me'},{message:'x'.repeat(3001)}])assert.equal(statusOf(()=>model.newPublicBooking(input(over))),400,JSON.stringify(over));});
test('customers cancel or reschedule instantly, with revision and timing checks',()=>{const b=model.newPublicBooking(input());assert.equal(statusOf(()=>model.customerChange(b,{action:'cancel',revision:3})),409);const canceled=model.customerChange(b,{action:'cancel',revision:0});assert.equal(canceled.status,'canceled');assert.equal(canceled.revision,1);assert.equal(statusOf(()=>model.customerChange(canceled,{action:'cancel',revision:1})),409);const moved=model.customerChange(b,{action:'reschedule',revision:0,appointment:'installation-consultation',date:phoenixDay(9),time:'13:00'});assert.equal(moved.status,'rescheduled');assert.equal(moved.title,'Installation consultation');assert.equal(Date.parse(moved.end_time)-Date.parse(moved.start_time),90*60000);assert.equal(moved.history.at(-1).action,'rescheduled');assert.equal(statusOf(()=>model.customerChange(b,{action:'reschedule',revision:0,appointment:'surface-consultation',date:input().date,time:'09:30'})),400);assert.equal(statusOf(()=>model.customerChange({...b,start_time:new Date(Date.now()-3600000).toISOString()},{action:'cancel',revision:0})),409);assert.equal(statusOf(()=>model.customerChange(b,{action:'delete',revision:0})),400);});
test('staff updates validate status and assignment and record history',()=>{const b=model.newPublicBooking(input()),members=[{id:'m1',role:'staff'},{id:'v1',role:'viewer'}];assert.equal(statusOf(()=>model.staffUpdate(b,{revision:0,status:'bogus'},members,'Jo')),400);assert.equal(statusOf(()=>model.staffUpdate(b,{revision:0,status:'confirmed',assigned_staff_id:'v1'},members,'Jo')),400);assert.equal(statusOf(()=>model.staffUpdate(b,{revision:0,status:'confirmed',related_order_id:'x'},members,'Jo')),400);assert.equal(statusOf(()=>model.staffUpdate(b,{revision:2,status:'confirmed'},members,'Jo')),409);assert.equal(model.staffUpdate(b,{revision:0,status:'pending',internal_notes:''},members,'Jo'),b);const next=model.staffUpdate(b,{revision:0,status:'confirmed',assigned_staff_id:'m1',internal_notes:'Bring samples'},members,'Jo');assert.equal(next.status,'confirmed');assert.equal(next.revision,1);assert.match(next.history.at(-1).detail,/^Jo: status pending → confirmed/);});
test('customer view hides staff-only fields',()=>{const view=model.customerView({...model.newPublicBooking(input()),internal_notes:'secret',assigned_staff_id:'m1'});for(const key of ['internal_notes','assigned_staff_id','history'])assert.equal(key in view,false);assert.equal(view.minutes,30);assert.equal(view.can_change,true);});
test('booking emails escape customer values and render the call to action as a button',()=>{const b=model.newPublicBooking(input({firstName:'<script>alert(1)</script>'})),vars=model.bookingVariables(b,'https://layeredfx.com');const body=model.fillTemplate('<h1>Hi {{first_name}}</h1><p><a href="{{manage_url}}">Manage</a></p><p>{{unknown_tag}}</p>',vars);assert.ok(!body.includes('<script>'));assert.ok(body.includes('&lt;script&gt;'));assert.ok(body.includes('{{unknown_tag}}'));const html=model.emailHtml({bodyHtml:body,preheader:'Soon',origin:'https://layeredfx.com'});assert.match(html,/background:#d6ff41"><a href="https:\/\/layeredfx\.com\/portal\/bookings" style=/);assert.equal((html.match(/<a [^>]*style="[^"]*"[^>]*style=/g)||[]).length,0);assert.match(model.emailText(body),/Manage: https:\/\/layeredfx\.com\/portal\/bookings/);assert.equal(model.fillText('Hi {{first_name}}\nthere',{first_name:'A'}),'Hi A there');});

const boundary=dataUrl(`export const fixture={saves:[],notifies:[],bookings:new Map(),role:'staff',portalEmail:'ana@example.com'};
export function checkOrigin(r){if(r.headers.get('origin')!=='https://layeredfx.com')throw Object.assign(new Error('Origin denied'),{status:403});}
export function errorResponse(e){return Response.json({message:e.message},{status:e.status||500});}
export function mode(){return 'supabase';}
export async function currentActor(){return {id:'m1',name:'Jo',email:'jo@layeredfx.com',role:fixture.role};}
export async function people(){return [{id:'m1',name:'Jo',email:'jo@layeredfx.com',role:'staff'}];}
export async function currentPortal(){if(!fixture.portalEmail)throw Object.assign(new Error('Sign in required.'),{status:401});return {email:fixture.portalEmail};}
export function portalDemo(){return false;}
export async function createBooking(b){fixture.saves.push(b);fixture.bookings.set(b.id,b);return b;}
export async function notifyBooking(b,event){fixture.notifies.push(event);return {customer:'sent'};}
export async function getBooking(id){return fixture.bookings.get(id)??null;}
export async function saveBooking(next,expected){fixture.saves.push({next,expected});fixture.bookings.set(next.id,next);return next;}
export async function listBookings(){return [...fixture.bookings.values()];}
export async function bookingsForEmail(email){return [...fixture.bookings.values()].filter(b=>b.customer_email===email);}
export async function listNotifications(){return [];}`);
const replacements={"'@/lib/operations/server'":`'${boundary}'`,"'@/lib/operations/security.mjs'":`'${security}'`,"'@/lib/operations/engine.mjs'":`'${engine}'`,"'@/lib/bookings/model'":`'${modelUrl}'`,"'@/lib/bookings/server'":`'${boundary}'`,"'@/lib/portal/server'":`'${boundary}'`,"'@/lib/bookings/catalog'":`'${catalog}'`};
const publicApi=await import(dataUrl(transpile('../app/api/bookings/route.ts',replacements)));
const portalApi=await import(dataUrl(transpile('../app/api/portal/bookings/route.ts',replacements)));
const adminApi=await import(dataUrl(transpile('../app/api/ctrlp/admin/bookings/route.ts',replacements)));
const {fixture}=await import(boundary);
const request=(path,body,{method='POST',origin='https://layeredfx.com',ip='203.0.113.1'}={})=>new Request('https://layeredfx.com'+path,{method,headers:{origin,'content-type':'application/json','x-forwarded-for':ip},body:typeof body==='string'?body:JSON.stringify(body)});

test('public booking rejects cross-origin, bots, bad JSON and oversized bodies without saving',async()=>{const saves=fixture.saves.length;assert.equal((await publicApi.POST(request('/api/bookings',input(),{origin:'https://evil.test',ip:'10.0.0.1'}))).status,403);assert.equal((await publicApi.POST(request('/api/bookings',input({website:'spam'}),{ip:'10.0.0.2'}))).status,400);assert.equal((await publicApi.POST(request('/api/bookings','not json',{ip:'10.0.0.3'}))).status,400);assert.equal((await publicApi.POST(request('/api/bookings','x'.repeat(12001),{ip:'10.0.0.4'}))).status,413);assert.equal(fixture.saves.length,saves);assert.equal(fixture.notifies.length,0);});
test('public booking saves, notifies and returns only customer-safe fields',async()=>{const response=await publicApi.POST(request('/api/bookings',input(),{ip:'10.0.0.5'}));assert.equal(response.status,201);const data=await response.json();assert.equal(data.email,'sent');assert.equal(data.booking.title,'Surface consultation');assert.equal('internal_notes' in data.booking,false);assert.equal(fixture.notifies.at(-1),'booked');});
test('public booking is rate limited per client',async()=>{let last;for(let i=0;i<6;i++)last=await publicApi.POST(request('/api/bookings',input({firstName:''}),{ip:'198.51.100.9'}));assert.equal(last.status,429);});
test('portal lists and changes only the signed-in customer’s appointments',async()=>{const mine=model.newPublicBooking(input()),theirs=model.newPublicBooking(input({email:'other@example.com'}));fixture.bookings.set(mine.id,mine);fixture.bookings.set(theirs.id,theirs);const listed=await (await portalApi.GET()).json();assert.ok(listed.bookings.length>0&&listed.bookings.every(b=>b.customer_email==='ana@example.com'));assert.equal((await portalApi.PATCH(request('/api/portal/bookings',{id:theirs.id,revision:0,action:'cancel'},{method:'PATCH'}))).status,404);assert.equal((await portalApi.PATCH(request('/api/portal/bookings',{id:mine.id,revision:0,action:'cancel'},{method:'PATCH',origin:'https://evil.test'}))).status,403);const response=await portalApi.PATCH(request('/api/portal/bookings',{id:mine.id,revision:0,action:'cancel'},{method:'PATCH'}));assert.equal(response.status,200);assert.equal((await response.json()).booking.status,'canceled');assert.equal(fixture.saves.at(-1).expected,0);assert.equal(fixture.notifies.at(-1),'canceled');fixture.portalEmail='';assert.equal((await portalApi.GET()).status,401);fixture.portalEmail='ana@example.com';});
test('dashboard bookings reject viewers, keep unconnected resources honest and use revisions',async()=>{const b=model.newPublicBooking(input({email:'staff-test@example.com'}));fixture.bookings.set(b.id,b);fixture.role='viewer';assert.equal((await adminApi.PATCH(request('/api/ctrlp/admin/bookings',{resource:'appointment',id:b.id,revision:0,status:'confirmed'},{method:'PATCH'}))).status,403);fixture.role='staff';const typeResponse=await adminApi.POST(request('/api/ctrlp/admin/bookings',{resource:'appointment_type',name:'X'}));assert.equal(typeResponse.status,503);assert.equal((await typeResponse.json()).configurationRequired,true);const updated=await adminApi.PATCH(request('/api/ctrlp/admin/bookings',{resource:'appointment',id:b.id,revision:0,status:'confirmed',assigned_staff_id:'m1',internal_notes:'Call first'},{method:'PATCH'}));assert.equal(updated.status,200);assert.equal((await updated.json()).appointment.status,'confirmed');assert.equal((await adminApi.PATCH(request('/api/ctrlp/admin/bookings',{resource:'appointment',id:b.id,revision:0,status:'completed'},{method:'PATCH'}))).status,409);const listed=await (await adminApi.GET(new Request('https://layeredfx.com/api/ctrlp/admin/bookings'))).json();const summary=await (await adminApi.GET(new Request('https://layeredfx.com/api/ctrlp/admin/bookings?summary=1'))).json();assert.ok(Number.isInteger(summary.upcoming)&&summary.upcoming>=1);assert.equal('appointments' in summary,false);assert.ok(Array.isArray(summary.next)&&summary.next.length<=5&&summary.next.some(n=>n.id===b.id&&n.start_time===b.start_time));assert.ok(summary.next.every(n=>!('customer_email' in n)&&!('internal_notes' in n)));assert.ok(listed.appointments.some(a=>a.id===b.id&&a.appointment_type_id==='surface-consultation'));});
test('adding a booking to Leads and Pipeline keeps appointment details and never duplicates records',async()=>{const {applyCommand,emptyState}=await import(engine);const actor={id:'m1',name:'Jo',role:'staff'};let state={...emptyState(),people:[actor]};const booking=model.operationsBooking(model.newPublicBooking(input({email:'convert@example.com',message:'Wrap the island'})));for(let i=0;i<2;i++)state=applyCommand(state,{type:'booking.import',booking},actor).state;assert.equal(state.leads.length,1);assert.equal(state.leads[0].source,'Booking');assert.equal(state.leads[0].email,'convert@example.com');assert.equal(state.leads[0].bookings.length,1);for(let i=0;i<2;i++)state=applyCommand(state,{type:'booking.pipeline',booking},actor).state;assert.equal(state.leads.length,1);assert.equal(state.deals.length,1);assert.equal(state.leads[0].opportunityId,state.deals[0].id);assert.match(state.deals[0].notes,new RegExp(`Booking ${booking.id}: Surface consultation`));assert.match(state.deals[0].notes,/Wrap the island/);assert.equal(state.deals[0].notes.split(`Booking ${booking.id}`).length,2);assert.throws(()=>applyCommand(state,{type:'booking.import',booking:{id:'x'}},actor),/Invalid booking/);assert.throws(()=>applyCommand(state,{type:'booking.import',booking},{...actor,role:'viewer'}),/read-only/);});
