import test from 'node:test';
import assert from 'node:assert/strict';
import {applyCommand,emptyState,access,visibleState,OperationError,validDate,today,offsetDate,stats,needsNextStep,stepsFor,blockingSteps,DEFAULT_STAGES,STAGES,PATH,OPEN,plainText,demoState} from '../lib/operations/engine.mjs';

const NOW='2026-09-10T19:00:00.000Z';
const ADMIN={id:'admin',name:'Admin',role:'admin',email:'admin@example.test'};
const OWNER={id:'owner',name:'Owner',role:'staff',email:'owner@example.test'};
const OTHER={id:'other',name:'Other',role:'staff',email:'other@example.test'};
const VIEWER={id:'viewer',name:'Viewer',role:'viewer',email:'viewer@example.test'};
const fixture=()=>Object.assign(emptyState(),{people:[ADMIN,OWNER,OTHER,VIEWER]});
function run(state,command,actor=OWNER,at=NOW){return applyCommand(state,command,actor,at);}
function dealFixture(){const r=run(fixture(),{type:'deal.create',name:'Kitchen wrap',client:'Test client',email:'client@example.test',value:5000,closeDate:'2026-09-30'});return {state:r.state,id:r.resultId};}
function documentFixture(scope='personal'){const r=run(fixture(),{type:'document.create',title:'Private scope',scope,templateId:'scope'});return {state:r.state,id:r.resultId};}
function planFixture(visibility='private',templateId='blank'){const r=run(fixture(),{type:'plan.create',name:'Test installation',visibility,templateId});return {state:r.state,id:r.resultId};}
const rejected=(fn,status,pattern)=>assert.throws(fn,e=>e instanceof OperationError&&e.status===status&&(!pattern||pattern.test(e.message)));
const textNodes=text=>[{type:'p',children:[{text}]}];

// Pipeline and stage rules use the same reducer in demo and authenticated API mode.
test('stable Channel Cast stage identities retained',()=>{assert.deepEqual(STAGES,[...PATH,'closed_lost','nurture']);assert.equal(STAGES.length,9);assert(!OPEN.includes('nurture'));assert.equal(DEFAULT_STAGES.proposal.label,'Estimate / Proposal');});
test('commands do not mutate their input',()=>{const s=fixture();const before=structuredClone(s);const r=run(s,{type:'deal.create',name:'New'});assert.deepEqual(s,before);assert.equal(r.state.revision,1);});
test('unknown command fails closed',()=>rejected(()=>run(fixture(),{type:'store.replace',state:{}}),400));
test('anonymous actor cannot mutate',()=>rejected(()=>run(fixture(),{type:'deal.create',name:'Test'},null),401));
test('global viewer is read-only',()=>rejected(()=>run(fixture(),{type:'deal.create',name:'Test'},VIEWER),403));
test('missing opportunity name is rejected',()=>rejected(()=>run(fixture(),{type:'deal.create',name:'  '}),400,/required/));
test('lead conversion reuses opportunity and contact on repeat',()=>{let r=run(fixture(),{type:'lead.create',name:'Lead',email:'lead@example.test',owner:OTHER.id});const leadId=r.resultId;r=run(r.state,{type:'lead.convert',id:leadId,value:2000});const firstId=r.resultId;r=run(r.state,{type:'lead.convert',id:leadId,value:99999});assert.equal(r.resultId,firstId);assert.equal(r.state.deals.length,1);assert.equal(r.state.contacts.length,1);assert.equal(r.state.deals[0].owner,OTHER.id);assert.equal(r.state.deals[0].leadId,leadId);assert.equal(r.state.deals[0].value,2000);});
test('same email reuses contact without merging distinct opportunities',()=>{let {state}=dealFixture();state=run(state,{type:'deal.create',name:'Second project',email:'CLIENT@example.test'}).state;assert.equal(state.contacts.length,1);assert.equal(state.deals.length,2);assert.equal(state.deals[0].contactId,state.deals[1].contactId);});
test('generic edit cannot bypass stage transition',()=>{const {state,id}=dealFixture();rejected(()=>run(state,{type:'deal.update',id,patch:{stage:'closed_won'}}),400,/transition/);});
test('required first-stage next action blocks board move',()=>{const {state,id}=dealFixture();rejected(()=>run(state,{type:'deal.stage',id,stage:'contacted'}),400,/required/);});
test('a valid next action permits first stage advancement',()=>{let {state,id}=dealFixture();state=run(state,{type:'deal.next',id,action:'Call client',dueDate:'2026-09-11'}).state;state=run(state,{type:'deal.stage',id,stage:'contacted'}).state;assert.equal(state.deals[0].stage,'contacted');assert.equal(state.deals[0].probability,20);assert.equal(state.deals[0].stageHistory.length,2);});
test('skipping ahead checks intermediate requirements',()=>{let {state,id}=dealFixture();state=run(state,{type:'deal.next',id,action:'Call',dueDate:'2026-09-11'}).state;rejected(()=>run(state,{type:'deal.stage',id,stage:'negotiation'}),400,/Contacted/);});
test('staff cannot invoke admin override',()=>{const {state,id}=dealFixture();rejected(()=>run(state,{type:'deal.stage',id,stage:'proposal',overrideReason:'I bypassed checks'}),400);});
test('admin override requires a reason and logs it',()=>{const {state,id}=dealFixture();rejected(()=>run(state,{type:'deal.stage',id,stage:'proposal'},ADMIN),400);const r=run(state,{type:'deal.stage',id,stage:'proposal',overrideReason:'Documented prior scope approval'},ADMIN);assert.equal(r.state.deals[0].stageHistory.at(-1).overrideReason,'Documented prior scope approval');assert.match(r.state.activities.at(-1).body,/Admin override/);});
test('automatic checklist cannot be marked manually',()=>{const {state,id}=dealFixture();rejected(()=>run(state,{type:'deal.check',id,stage:'new_working',itemId:'owner',done:true}),400,/automatically/);assert.equal(stepsFor(state,state.deals[0]).find(i=>i.id==='owner').done,true);});
test('extra required opportunity step blocks transition',()=>{let {state,id}=dealFixture();state=run(state,{type:'deal.next',id,action:'Call',dueDate:'2026-09-11'}).state;state=run(state,{type:'deal.extra',id,stage:'new_working',label:'Confirm tenant permission',required:true}).state;rejected(()=>run(state,{type:'deal.stage',id,stage:'contacted'}),400,/tenant/);const item=state.deals[0].extraItems[0];state=run(state,{type:'deal.check',id,stage:'new_working',itemId:item.id,done:true}).state;assert.equal(blockingSteps(state,state.deals[0]).length,0);});
test('stage configuration is admin only and enforces stable auto predicates',()=>{const {state}=dealFixture();const config=structuredClone(DEFAULT_STAGES.new_working);config.items[0].auto=null;rejected(()=>run(state,{type:'stage.configure',stage:'new_working',config}),403);const r=run(state,{type:'stage.configure',stage:'new_working',config},ADMIN);assert.equal(r.state.stageConfig.new_working.items[0].auto,'owner');});
test('stage configuration rejects duplicate step IDs',()=>{const config=structuredClone(DEFAULT_STAGES.new_working);config.items.push(config.items[0]);rejected(()=>run(fixture(),{type:'stage.configure',stage:'new_working',config},ADMIN),400,/unique/);});
test('stage configuration reset restores default and history stays',()=>{let {state,id}=dealFixture();const config={...structuredClone(DEFAULT_STAGES.new_working),label:'Incoming',probability:12};state=run(state,{type:'stage.configure',stage:'new_working',config},ADMIN).state;const history=structuredClone(state.deals[0].stageHistory);state=run(state,{type:'stage.configure',stage:'new_working',reset:true},ADMIN).state;assert.equal(state.stageConfig.new_working,undefined);assert.deepEqual(state.deals.find(d=>d.id===id).stageHistory,history);});
test('lost requires a reason; history and value remain',()=>{const {state,id}=dealFixture();rejected(()=>run(state,{type:'deal.stage',id,stage:'closed_lost'}),400,/reason/);const r=run(state,{type:'deal.stage',id,stage:'closed_lost',lostReason:'Timing',lostNotes:'Revisit next year'});assert.equal(r.state.deals[0].value,5000);assert.equal(r.state.deals[0].probability,0);assert.equal(r.state.deals[0].closedAt,NOW);});
test('closed opportunities require a reason before reopening',()=>{let {state,id}=dealFixture();state=run(state,{type:'deal.stage',id,stage:'closed_lost',lostReason:'Timing'}).state;rejected(()=>run(state,{type:'deal.stage',id,stage:'new_working'}),400,/reopen/);state=run(state,{type:'deal.stage',id,stage:'new_working',reason:'Client ready to resume'}).state;assert.equal(state.deals[0].closedAt,null);assert.equal(state.deals[0].reopenedAt,NOW);assert.equal(state.deals[0].lostReason,'Timing');assert.equal(state.deals[0].stageHistory.length,3);});
test('won requires positive value and summary; conversion is idempotent',()=>{let {state,id}=dealFixture();rejected(()=>run(state,{type:'deal.stage',id,stage:'closed_won',overrideReason:'Approved'},ADMIN),400,/summary/);state=run(state,{type:'deal.stage',id,stage:'closed_won',wonSummary:'Signed scope',overrideReason:'Approval reviewed'},ADMIN).state;assert.equal(state.contacts[0].type,'client');assert.equal(state.projects.length,1);state=run(state,{type:'deal.stage',id,stage:'new_working',reason:'Additional scope'}).state;state=run(state,{type:'deal.stage',id,stage:'closed_won',wonSummary:'Re-approved',overrideReason:'Approval reviewed'},ADMIN).state;assert.equal(state.projects.length,1);});
test('won probability stays 100 on generic edit',()=>{let {state,id}=dealFixture();state=run(state,{type:'deal.stage',id,stage:'closed_won',wonSummary:'Approved',overrideReason:'Reviewed'},ADMIN).state;state=run(state,{type:'deal.update',id,patch:{probability:30}}).state;assert.equal(state.deals[0].probability,100);});
test('nurture requires a current or future revisit date',()=>{let {state,id}=dealFixture();rejected(()=>run(state,{type:'deal.stage',id,stage:'nurture'}),400,/revisit/);state=run(state,{type:'deal.next',id,action:'Revisit',dueDate:'2026-09-09'}).state;rejected(()=>run(state,{type:'deal.stage',id,stage:'nurture'}),400);state=run(state,{type:'deal.next',id,action:'Revisit',dueDate:'2026-10-10'}).state;state=run(state,{type:'deal.stage',id,stage:'nurture'}).state;assert.equal(stats(state.deals).openCount,0);});
test('owner changes append history',()=>{const {state,id}=dealFixture();const r=run(state,{type:'deal.update',id,patch:{owner:OTHER.id}});assert.equal(r.state.deals[0].ownerHistory.length,2);assert.equal(r.state.deals[0].ownerHistory.at(-1).owner,OTHER.id);});
test('invalid numbers and non-member owners rejected',()=>{const {state,id}=dealFixture();rejected(()=>run(state,{type:'deal.update',id,patch:{value:-1}}),400);rejected(()=>run(state,{type:'deal.update',id,patch:{probability:101}}),400);rejected(()=>run(state,{type:'deal.update',id,patch:{owner:'unknown'}}),400);});
test('archived opportunity is retained and cannot be edited until restored',()=>{let {state,id}=dealFixture();state=run(state,{type:'deal.archive',id}).state;assert.equal(stats(state.deals).openCount,0);rejected(()=>run(state,{type:'deal.next',id,action:'Call',dueDate:'2026-09-11'}),400,/Restore/);state=run(state,{type:'deal.archive',id,restore:true}).state;assert.equal(stats(state.deals).openCount,1);});
test('custom fields support validated dates and numbers',()=>{let {state,id}=dealFixture();state=run(state,{type:'deal.field',id,label:'Area',fieldType:'number',value:'122.5'}).state;const fieldId=state.deals[0].customFields[0].id;state=run(state,{type:'deal.field',id,fieldId,label:'Area',fieldType:'number',value:'130'}).state;assert.equal(state.deals[0].customFields.length,1);rejected(()=>run(state,{type:'deal.field',id,label:'Date',fieldType:'date',value:'2026-02-30'}),400);});
test('manual activity is logged without executing communications',()=>{const {state,id}=dealFixture();const r=run(state,{type:'deal.activity',id,kind:'invoice',body:'Recorded approved estimate'});assert.equal(r.state.activities.at(-1).kind,'invoice');assert.equal(r.state.activities.at(-1).actorId,OWNER.id);});
test('today due dates are not overdue in Phoenix',()=>{assert.equal(today(new Date('2026-09-11T01:00:00Z')),'2026-09-10');assert.equal(needsNextStep({stage:'proposal',nextStep:{dueDate:'2026-09-10'}},'2026-09-10'),false);});
test('date validator rejects impossible dates and permits leap years',()=>{assert.equal(validDate('2028-02-29'),'2028-02-29');rejected(()=>validDate('2026-02-29'),400);rejected(()=>validDate('2026-99-99'),400);assert.equal(offsetDate('2026-12-31',1),'2027-01-01');});
test('forecast excludes nurture, closed and archived opportunities',()=>{assert.deepEqual(stats([{stage:'qualified',value:1000,probability:35},{stage:'nurture',value:500,probability:10},{stage:'closed_won',value:2000,probability:100},{stage:'closed_lost',value:100,probability:0},{stage:'proposal',value:9999,probability:65,archivedAt:NOW}]),{openCount:1,openValue:1000,weighted:350,wonValue:2000,winRate:50});});

// Workspace access, document persistence, versioning and hierarchy.
test('personal documents are not returned to another staff member',()=>{const {state}=documentFixture();assert.equal(visibleState(state,OTHER).documents.length,0);assert.equal(visibleState(state,OWNER).documents.length,1);assert.equal(visibleState(state,ADMIN).documents.length,1);});
test('direct document-ID access cannot bypass privacy',()=>{const {state,id}=documentFixture();rejected(()=>run(state,{type:'document.save',id,title:'Hijack',content_json:textNodes('x')},OTHER),403);});
test('shared documents editable by staff, not a viewer collaborator',()=>{let {state,id}=documentFixture('shared');assert.equal(access(state.documents[0],OTHER).edit,true);state=run(state,{type:'document.share',id,scope:'shared',collaborators:[{user_id:OTHER.id,permission:'viewer'}]}).state;assert.equal(access(state.documents[0],OTHER).edit,false);rejected(()=>run(state,{type:'document.save',id,title:'No',content_json:textNodes('x')},OTHER),403);});
test('editor collaborator can edit personal doc but cannot manage sharing',()=>{let {state,id}=documentFixture();state=run(state,{type:'document.share',id,scope:'personal',collaborators:[{user_id:OTHER.id,permission:'editor'}]}).state;state=run(state,{type:'document.save',id,title:'Shared edit',content_json:textNodes('Content')},OTHER).state;assert.equal(state.documents[0].title,'Shared edit');rejected(()=>run(state,{type:'document.share',id,scope:'shared',collaborators:[]},OTHER),403);});
test('saving creates searchable content and restorable prior version',()=>{let {state,id}=documentFixture();const original=structuredClone(state.documents[0].content_json);state=run(state,{type:'document.save',id,title:'Updated title',content_json:textNodes('Searchable selection brief')}).state;assert.equal(state.documents[0].plain_text,'Searchable selection brief');const versionId=state.documents[0].versions[0].id;state=run(state,{type:'document.restoreVersion',id,versionId}).state;assert.deepEqual(state.documents[0].content_json,original);assert.equal(state.documents[0].versions.length,2);});
test('version history is capped at 40 snapshots',()=>{let {state,id}=documentFixture();for(let i=0;i<45;i++)state=run(state,{type:'document.save',id,title:'Version '+i,content_json:textNodes('Content '+i)}).state;assert.equal(state.documents[0].versions.length,40);});
test('document content rejects unsafe links and oversized blocks',()=>{const {state,id}=documentFixture();rejected(()=>run(state,{type:'document.save',id,title:'Test',content_json:[{type:'a',url:'javascript:alert(1)',children:[{text:'Unsafe'}]}]}),400,/HTTP/);rejected(()=>run(state,{type:'document.save',id,title:'Test',content_json:textNodes('x'.repeat(350001))}),400,/limit/);});
test('nested folders cannot cross workspace boundary',()=>{let s=fixture();s=run(s,{type:'folder.create',name:'Parent'}).state;const parent=s.folders[0].id;s=run(s,{type:'workspace.create',name:'Second workspace'}).state;rejected(()=>run(s,{type:'folder.create',name:'Child',workspaceId:s.workspaces[1].id,parentId:parent}),403);});
test('documents cannot move into another users personal folder',()=>{let {state,id}=documentFixture();state=run(state,{type:'folder.create',name:'Other private'},OTHER).state;rejected(()=>run(state,{type:'document.move',id,folderId:state.folders[0].id}),403);});
test('favorite toggles without duplicate entries',()=>{let {state,id}=documentFixture();state=run(state,{type:'document.favorite',id}).state;assert.deepEqual(state.documents[0].favorite_user_ids,[OWNER.id]);state=run(state,{type:'document.favorite',id}).state;assert.deepEqual(state.documents[0].favorite_user_ids,[]);});
test('archive prevents editing and retains prior data',()=>{let {state,id}=documentFixture();state=run(state,{type:'document.archive',id}).state;rejected(()=>run(state,{type:'document.save',id,title:'No',content_json:textNodes('x')}),403);state=run(state,{type:'document.archive',id,restore:true}).state;assert.equal(state.documents[0].archived_at,null);});
test('comments follow document visibility and resolution permissions',()=>{let {state,id}=documentFixture();state=run(state,{type:'document.comment',id,body:'Confirm finish code'}).state;assert.equal(visibleState(state,OTHER).comments.length,0);const commentId=state.comments[0].id;rejected(()=>run(state,{type:'comment.resolve',id:commentId},OTHER),403);state=run(state,{type:'comment.resolve',id:commentId}).state;assert.equal(state.comments[0].resolved_at,NOW);});
test('invalid collaborator membership is rejected',()=>{const {state,id}=documentFixture();rejected(()=>run(state,{type:'document.share',id,scope:'personal',collaborators:[{user_id:'unknown',permission:'editor'}]}),400);});
test('plain-text extraction handles nested table text',()=>assert.equal(plainText([{type:'table',children:[{type:'tr',children:[{type:'td',children:textNodes('Cell')}]}]}]),'Cell'));

// Plan and task integrity, memberships, templates and view consistency.
test('private plans and their tasks are filtered together',()=>{const {state}=planFixture('private','surface');assert(state.tasks.length>0);assert.equal(visibleState(state,OTHER).plans.length,0);assert.equal(visibleState(state,OTHER).tasks.length,0);});
test('task ID cannot be moved into a different plan',()=>{let {state,id}=planFixture('team','surface');const taskId=state.tasks[0].id;const r=run(state,{type:'plan.create',name:'Other plan',visibility:'team'});state=r.state;rejected(()=>run(state,{type:'task.save',id:taskId,planId:r.resultId,patch:{title:'Oops'}}),400,/belong/);assert.notEqual(id,r.resultId);});
test('template builds fresh task and checklist identities per plan',()=>{let {state}=planFixture('team','surface');state=run(state,{type:'plan.create',name:'Second',templateId:'surface',visibility:'team'}).state;const ids=state.tasks.flatMap(t=>[t.id,...t.checklist.map(c=>c.id)]);assert.equal(new Set(ids).size,ids.length);});
test('opportunity-to-plan once operation is idempotent',()=>{let {state,id}=dealFixture();let r=run(state,{type:'plan.create',opportunityId:id,templateId:'surface',once:true});const planId=r.resultId;r=run(r.state,{type:'plan.create',opportunityId:id,templateId:'surface',once:true});assert.equal(r.resultId,planId);assert.equal(r.state.plans.length,1);});
test('cannot discover another private linked plan using once',()=>{let {state,id}=dealFixture();state=run(state,{type:'plan.create',opportunityId:id,once:true,visibility:'private'}).state;rejected(()=>run(state,{type:'plan.create',opportunityId:id,once:true},OTHER),403);});
test('viewer member cannot modify a team plan',()=>{let {state,id}=planFixture('team','surface');state=run(state,{type:'plan.update',id,patch:{members:[{user_id:OTHER.id,role:'viewer'}]}}).state;assert.equal(access(state.plans[0],OTHER,'plan').edit,false);rejected(()=>run(state,{type:'task.save',id:state.tasks[0].id,planId:id,patch:{title:'No'}},OTHER),403);});
test('editor member can work but not change plan membership',()=>{let {state,id}=planFixture('private');state=run(state,{type:'plan.update',id,patch:{members:[{user_id:OTHER.id,role:'editor'}]}}).state;state=run(state,{type:'task.save',planId:id,patch:{title:'Sample task'}},OTHER).state;assert.equal(state.tasks.length,1);rejected(()=>run(state,{type:'plan.update',id,patch:{visibility:'team'}},OTHER),403);});
test('plan date ranges are validated',()=>{const {state,id}=planFixture();rejected(()=>run(state,{type:'plan.update',id,patch:{start_date:'2026-10-01',target_date:'2026-09-01'}}),400,/date/);});
test('task completion synchronizes percentage and timestamp in all views',()=>{let {state,id}=planFixture('team','surface');const taskId=state.tasks[0].id;state=run(state,{type:'task.save',id:taskId,planId:id,patch:{status:'complete',progress:40}}).state;assert.equal(state.tasks[0].progress,100);assert.equal(state.tasks[0].completed_at,NOW);state=run(state,{type:'task.save',id:taskId,planId:id,patch:{status:'in_progress'}}).state;assert.equal(state.tasks[0].completed_at,null);assert(state.tasks[0].progress<100);});
test('task dates, priorities, progress and groups validated',()=>{const {state,id}=planFixture();rejected(()=>run(state,{type:'task.save',planId:id,patch:{title:'Bad',start_date:'2026-10-01',due_date:'2026-09-01'}}),400);rejected(()=>run(state,{type:'task.save',planId:id,patch:{title:'Bad',priority:'critical'}}),400);rejected(()=>run(state,{type:'task.save',planId:id,patch:{title:'Bad',progress:150}}),400);rejected(()=>run(state,{type:'task.save',planId:id,patch:{title:'Bad',group_id:'unknown'}}),400);});
test('private plan assignee must already have access',()=>{const {state,id}=planFixture();rejected(()=>run(state,{type:'task.save',planId:id,patch:{title:'Task',assignee_ids:[OTHER.id]}}),400,/Invite/);});
test('read-only user cannot receive assigned tasks',()=>{const {state,id}=planFixture('team');rejected(()=>run(state,{type:'task.save',planId:id,patch:{title:'Task',assignee_ids:[VIEWER.id]}}),400,/read-only/);});
test('labels and task labels remain referentially valid',()=>{let {state,id}=planFixture('team');state=run(state,{type:'plan.label',id,name:'Installation',color:'olive'}).state;const label=state.plans[0].labels[0].id;state=run(state,{type:'task.save',planId:id,patch:{title:'Task',label_ids:[label]}}).state;assert.deepEqual(state.tasks[0].label_ids,[label]);rejected(()=>run(state,{type:'task.save',id:state.tasks[0].id,planId:id,patch:{label_ids:['unknown']}}),400);});
test('nonempty group cannot be deleted until tasks moved',()=>{const {state,id}=planFixture('team','surface');rejected(()=>run(state,{type:'plan.group',id,removeId:state.tasks[0].group_id}),400,/Move tasks/);});
test('archiving plan blocks task edits and allows explicit restore',()=>{let {state,id}=planFixture('team','surface');state=run(state,{type:'plan.archive',id}).state;rejected(()=>run(state,{type:'task.save',id:state.tasks[0].id,planId:id,patch:{title:'Blocked'}}),403);rejected(()=>run(state,{type:'plan.update',id,patch:{name:'Blocked'}}),400,/Restore/);state=run(state,{type:'plan.archive',id,restore:true}).state;assert.equal(access(state.plans[0],OWNER,'plan').edit,true);});
test('task deletion removes only the selected task',()=>{let {state,id}=planFixture('team','surface');const count=state.tasks.length;state=run(state,{type:'task.delete',id:state.tasks[0].id}).state;assert.equal(state.tasks.length,count-1);assert.equal(state.plans[0].id,id);});
test('synthetic demo relationships are internally consistent',()=>{const s=demoState();assert(s.deals.length===4);assert(s.documents.length===1);assert(s.plans.length===1);assert(s.tasks.every(t=>s.plans.some(p=>p.id===t.plan_id)));assert(s.contacts.every(c=>c.email.endsWith('@example.test')));});
test('nurture cannot bypass intermediate required stage checks',()=>{let {state,id}=dealFixture();state=run(state,{type:'deal.next',id,action:'Revisit',dueDate:'2026-10-01'}).state;state=run(state,{type:'deal.stage',id,stage:'nurture'}).state;rejected(()=>run(state,{type:'deal.stage',id,stage:'closed_won',wonSummary:'Skipping steps'}),400,/required/);});
test('new opportunities use configured starting probability',()=>{let s=fixture();s=run(s,{type:'stage.configure',stage:'new_working',config:{...structuredClone(DEFAULT_STAGES.new_working),probability:17}},ADMIN).state;s=run(s,{type:'deal.create',name:'Configured stage'}).state;assert.equal(s.deals[0].probability,17);});
test('read-only team members cannot own active opportunities',()=>{const {state,id}=dealFixture();rejected(()=>run(state,{type:'deal.update',id,patch:{owner:VIEWER.id}}),400,/owner/);rejected(()=>run(state,{type:'deal.create',name:'Invalid',owner:VIEWER.id}),400,/owner/);});
