import test from 'node:test';import assert from 'node:assert/strict';import ts from 'typescript';import {readFileSync} from 'node:fs';import {createRequire} from 'node:module';import {pathToFileURL} from 'node:url';import twilio from 'twilio';
const url=source=>`data:text/javascript;base64,${Buffer.from(source).toString('base64')}`;const compile=file=>ts.transpileModule(readFileSync(new URL(file,import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText;
const engine=new URL('../lib/operations/engine.mjs',import.meta.url).href,sdk=pathToFileURL(createRequire(import.meta.url).resolve('twilio')).href;
const boundary=url(`import {OperationError} from '${engine}';export const fixture={role:'staff',reads:0};export async function people(){fixture.reads++;return [{id:'test_member',name:'Staff',role:fixture.role}];}export function errorResponse(error){return Response.json({message:error.message},{status:error.status||500});}`);
const{fixture}=await import(boundary);
const service=url(compile('../lib/communications/twilio.ts').replace("import 'server-only';",'').replace('"twilio"',JSON.stringify(sdk)).replace("'twilio'",JSON.stringify(sdk)).replace('@/lib/operations/engine.mjs',engine));
const api=await import(url(compile('../app/api/communications/voice/route.ts').replace('"twilio"',JSON.stringify(sdk)).replace("'twilio'",JSON.stringify(sdk)).replace('@/lib/operations/server',boundary).replace('@/lib/operations/engine.mjs',engine).replace('@/lib/communications/twilio',service)));
const endpoint='https://layeredfx.example/api/communications/voice',secret='fixture-auth-secret';
test.beforeEach(()=>{fixture.role='staff';fixture.reads=0;Object.assign(process.env,{LFX_TWILIO_ACCOUNT_SID:'AC'+'a'.repeat(32),LFX_TWILIO_AUTH_TOKEN:secret,LFX_TWILIO_PHONE_NUMBER:'+14805550123',LFX_TWILIO_VOICE_WEBHOOK_URL:endpoint});});
async function send(patch={},signed=true){const params={AccountSid:process.env.LFX_TWILIO_ACCOUNT_SID,From:'client:lfx_test_member',To:'+14805550999',...patch};return api.POST(new Request(endpoint,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded','X-Twilio-Signature':signed?twilio.getExpectedTwilioSignature(secret,endpoint,params):'bad'},body:new URLSearchParams(params)}));}
test('unsigned voice webhook cannot reach membership or dialing',async()=>{assert.equal((await send({},false)).status,403);assert.equal(fixture.reads,0);});
test('signed voice request uses the fixed caller and does not record',async()=>{const response=await send({CallerId:'+19999999999'});assert.equal(response.status,200);const xml=await response.text();assert.match(xml,/callerId="\+14805550123"/);assert.match(xml,/record="do-not-record"/);assert.ok(!xml.includes('+19999999999'));});
test('removed and read-only member identities cannot dial',async()=>{assert.equal((await send({From:'client:lfx_unknown'})).status,403);fixture.role='viewer';assert.equal((await send()).status,403);});
test('wrong account and unsafe destination are rejected',async()=>{assert.equal((await send({AccountSid:'AC'+'b'.repeat(32)})).status,403);assert.equal((await send({To:'<script>'})).status,400);});
