"use client";
import {useEffect,useState} from 'react';
import Link from 'next/link';
import Image from 'next/image';
import {ArrowRight,Eye,EyeOff,Layers,ShieldCheck} from 'lucide-react';
import {brand} from '@/lib/brand';
import {BrandedSelect} from '@/components/operations/branded-fields';
import {accountTypes} from '@/lib/portal/model';
export function PortalAuth({register=false,demo=false}:{register?:boolean;demo?:boolean}){
 const[show,setShow]=useState(false),[kind,setKind]=useState('residential'),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{if(location.hash.includes('access_token'))history.replaceState(null,'',location.pathname);},[]);
 useEffect(()=>{if(!demo&&!register)void fetch('/api/portal/auth/refresh',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'}).then(async res=>{if(res.ok){const data=await res.json();location.assign(data.destination);}}).catch(()=>{});},[demo,register]);
 return <main className="portal-auth"><section className="portal-auth-form"><Link href="/" aria-label="LayeredFX home"><Image src={brand.frontend.light} alt="LayeredFX" width={240} height={43} priority/></Link><h1>{register?'Make room for what’s next.':'Welcome back.'}</h1><p>{register?'Create your customer or partner account.':'Sign in to manage your projects, requests and conversations.'}</p><form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');setMessage('');const data=new FormData(e.currentTarget);try{const response=await fetch(`/api/portal/auth/${register?'register':'login'}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:data.get('email'),password:data.get('password'),name:data.get('name'),kind})});const result=await response.json();if(!response.ok)throw Error(result.message);if(result.destination)location.assign(result.destination);else setMessage(result.message);}catch(e){setError(e instanceof Error?e.message:'Please try again.');}finally{setBusy(false);}}}>
 {register&&<><label>Full name<input name="name" autoComplete="name" required maxLength={150}/></label><label>Account type<BrandedSelect value={kind} onChange={e=>setKind(e.target.value)}>{accountTypes.map(t=><option key={t} value={t}>{t==='contractor'?'General contractor':t[0].toUpperCase()+t.slice(1)}</option>)}</BrandedSelect></label>{['contractor','affiliate','vendor'].includes(kind)&&<p className="portal-hint">Partner accounts are reviewed by our team before access is approved.</p>}</>}
 <label>Email<input type="email" name="email" autoComplete="email" required maxLength={254}/></label><label>Password<div className="portal-password"><input type={show?'text':'password'} name="password" autoComplete={register?'new-password':'current-password'} required minLength={register?12:1} maxLength={1024}/><button type="button" aria-label={show?'Hide password':'Show password'} onClick={()=>setShow(!show)}>{show?<EyeOff size={18}/>:<Eye size={18}/>}</button></div></label>{register&&<small>Use at least 12 characters.</small>}{error&&<p role="alert" className="portal-error">{error}</p>}{message&&<p role="status">{message}</p>}<button className="portal-primary" disabled={busy||demo}>{busy?'Please wait…':register?'Create account':'Sign in'}<ArrowRight size={17}/></button></form>
 {demo&&<div className="portal-demo-links"><p>Local preview — live accounts are not connected yet.</p><Link href="/portal">Preview customer portal <ArrowRight size={14}/></Link><Link href="/partner">Preview partner portal <ArrowRight size={14}/></Link></div>}
 <p>{register?'Already have an account?':'New to LayeredFX?'} <Link href={register?'/login':'/register'}>{register?'Sign in':'Create an account'}</Link></p><Link href="/admin/login" className="portal-staff-link">Team sign-in</Link></section><aside className="portal-auth-story"><span className="portal-kicker"><ShieldCheck size={16}/> YOUR LAYEREDFX SPACE</span><h2>A new layer.<br/>A shared vision.</h2><p>From the first idea to the finishing details, keep your project and the people behind it connected.</p><div className="portal-story-art"><Layers size={100} strokeWidth={.7}/><span>Thoughtfully transformed.</span></div><div className="portal-story-bottom"><div><b>Your space</b><span>Residential & commercial</span></div><div><b>Your team</b><span>Customers & partners</span></div><div><b>Your next step</b><span>Plan. Share. Create.</span></div></div></aside></main>;
}
