"use client";
import {useEffect,useState} from 'react';
import Link from 'next/link';
import Image from 'next/image';
import {LayoutDashboard,CalendarDays,Package,HardHat,StickyNote,Images,MessageCircle,UserRound,ArrowUpRight,Moon,Sun,LogOut,Plus,Handshake,Truck} from 'lucide-react';
import {brand} from '@/lib/brand';
import {initialPortal,isPartner,portalCatalog,portalCommand,type PortalAccount,type PortalMedia} from '@/lib/portal/model';
import {BrandedInput} from '@/components/operations/branded-fields';
import {localMedia} from '@/lib/portal/local-media';
const sections=[['overview','Overview',LayoutDashboard],['bookings','Bookings',CalendarDays],['products','Products',Package],['services','Services & installation',HardHat],['notes','Project notes',StickyNote],['media','Photos & videos',Images],['messages','Messages',MessageCircle],['profile','Profile',UserRound]] as const;
export function PortalDashboard({initial,demo,section='overview'}:{initial:PortalAccount;demo:boolean;section?:string}){
 const[account,setAccount]=useState(initial),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[dark,setDark]=useState(false),[draft,setDraft]=useState<{kind:string;title:string}|null>(null);
 const partner=isPartner(account.kind),base=partner?'/partner':'/portal',key=`lfx:portal-preview:${initial.kind}`;
 useEffect(()=>{setAccount(initial);if(demo){try{const stored=localStorage.getItem(key);if(stored)setAccount(JSON.parse(stored));}catch{setError('Preview data could not be loaded.');}}setDark(localStorage.getItem('lfx:portal:theme')==='dark');},[demo,key,initial]);
 async function save(command:Record<string,unknown>){setBusy(true);setError('');try{let next:PortalAccount;if(demo){next=portalCommand(account,command);localStorage.setItem(key,JSON.stringify(next));}else{const res=await fetch('/api/portal',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({revision:account.revision,command})});next=await res.json();if(!res.ok)throw Error((next as unknown as {message:string}).message);}setAccount(next);setNotice(demo?'Saved in this browser.':'Saved to your account.');return true;}catch(e){setError(e instanceof Error?e.message:'Could not save.');return false;}finally{setBusy(false);}}
 const active=account.status==='active',items=account.state.items;
 const kinds:Record<string,string>={bookings:'booking',services:'service',products:'product',notes:'note',messages:'message',referrals:'referral',supply:'supply'};
 const title=section==='overview'?(partner?'Your partner workspace.':'Your space, coming together.'):section==='referrals'?'Referrals':section==='supply'?'Vendor submissions':sections.find(s=>s[0]===section)?.[1]||'Overview';
 const nav=partner?[...sections.slice(0,7),['referrals','Referrals',Handshake] as const,['supply','Vendor submissions',Truck] as const,sections[7]]:sections;
 return <div className={`portal ${dark?'dark':''}`}><aside className="portal-sidebar"><Link href={base}><Image src={brand.dashboard.dark} alt="LayeredFX" width={205} height={29}/></Link><p>{partner?'PARTNER PORTAL':'CUSTOMER PORTAL'}</p><nav aria-label="Portal navigation">{nav.map(([id,label,Icon])=><Link href={id==='overview'?base:`${base}/${id}`} key={id} aria-current={section===id?'page':undefined}><Icon size={19}/>{label}</Link>)}</nav><Link href="/" className="portal-site-link">Visit website <ArrowUpRight size={16}/></Link></aside><div className="portal-body"><header className="portal-topbar"><span>{account.kind==='contractor'?'General contractor':account.kind} <span className="portal-status">{account.status}</span></span><div><button aria-label="Toggle portal theme" onClick={()=>{setDark(!dark);localStorage.setItem('lfx:portal:theme',dark?'light':'dark');}}>{dark?<Sun size={20}/>:<Moon size={20}/>}</button><span>{account.state.profile.name}</span><button aria-label="Sign out" onClick={async()=>{if(!demo)await fetch('/api/portal/auth/logout',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});location.assign('/login');}}><LogOut size={18}/></button></div></header>{demo&&<div className="portal-preview">LOCAL PREVIEW · Changes stay in this browser. No booking, message or order is sent. <Link href={partner?'/portal':'/partner'}>Preview {partner?'customer':'partner'} portal</Link></div>}<main className="portal-main"><div className="portal-heading"><div><span className="portal-kicker">LAYEREDFX / {partner?'PARTNERS':'YOUR PROJECT'}</span><h1>{title}</h1><p>{partner?'Build your next project with LayeredFX.':'A place for your plans, details and conversations.'}</p></div>{kinds[section]&&active&&<button className="portal-primary" onClick={()=>setDraft({kind:kinds[section],title:''})}><Plus size={17}/>{section==='messages'?'New message':section==='notes'?'Add note':'New request'}</button>}</div>
 {error&&<div className="portal-error" role="alert">{error} <button onClick={()=>location.reload()}>Reload latest</button></div>}{notice&&<p role="status">{notice}</p>}
 {!active&&<section className="portal-card"><h2>Thanks for joining us.</h2><p>Your partner application is awaiting staff approval. You can update your profile while the team reviews it.</p></section>}
 {section==='overview'&&<><section className="portal-welcome"><div><span>THE NEXT LAYER</span><h2>{partner?'Good work starts with a good partnership.':'Let’s bring your vision to the surface.'}</h2><p>{partner?'Share opportunities, coordinate installation and keep your team connected.':'Tell us about your space, explore materials, and plan your next step.'}</p><Link href={`${base}/bookings`}>Plan a consultation <ArrowUpRight size={17}/></Link></div><div className="portal-welcome-art"><Image src={brand.app} alt="" width={120} height={120}/></div></section><div className="portal-metrics">{[['Open requests',items.filter(i=>i.status==='requested').length],['Bookings',items.filter(i=>i.kind==='booking').length],['Photos & videos',account.state.media.length],['Team replies',items.filter(i=>i.kind==='message'&&i.author==='team').length]].map(([label,value])=><section className="portal-card" key={label}><span>{label}</span><b>{value}</b></section>)}</div><div className="portal-grid"><section className="portal-card"><h2>Recent activity</h2>{items.slice(-4).reverse().map(i=><article className="portal-record" key={i.id}><b>{i.title}</b><span>{i.kind} · {i.status}</span></article>)}{!items.length&&<p>Your requests and conversations will appear here.</p>}</section><section className="portal-card"><h2>A few details go a long way.</h2><p>Add measurements, inspiration and photos to help the team understand your project.</p><Link href={`${base}/media`}>Add project media →</Link><Link href={`${base}/profile`}>Complete your profile →</Link></section></div></>}
 {active&&['products','services'].includes(section)&&<div className="portal-catalog">{portalCatalog.filter(p=>p.kind===kinds[section]).map(p=><section className="portal-card" key={p.name}><Package size={28}/><h2>{p.name}</h2><p>{p.description}</p><button onClick={()=>setDraft({kind:p.kind,title:p.name})}>Ask about {p.kind==='product'?'this product':'this service'} <ArrowUpRight size={15}/></button></section>)}</div>}
 {draft&&active&&<section className="portal-card portal-compose"><h2>{draft.kind==='message'?'Message the LayeredFX team':draft.kind==='note'?'Project note':'Tell us what you need'}</h2><form onSubmit={async e=>{e.preventDefault();const form=new FormData(e.currentTarget);if(await save({type:'item',kind:draft.kind,title:form.get('title'),body:form.get('body'),date:form.get('date')||''}))setDraft(null);}}><label>Title<input name="title" required maxLength={180} defaultValue={draft.title}/></label><label>Details<textarea name="body" required maxLength={4000} rows={4}/></label>{!['message','note'].includes(draft.kind)&&<label>Preferred date (optional)<BrandedInput type="date" name="date"/></label>}<p>{draft.kind==='note'?'Project notes are shared with the LayeredFX team.':draft.kind==='message'?'This conversation is between your account and the LayeredFX team.':'This is a request. Dates, availability and pricing are confirmed separately by the team.'}</p><div className="portal-actions"><button className="portal-primary" disabled={busy}>{busy?'Saving…':demo?'Save preview':draft.kind==='message'?'Send message':'Submit'}</button><button type="button" onClick={()=>setDraft(null)}>Cancel</button></div></form></section>}
 {active&&kinds[section]&&<section className="portal-card"><h2>{section==='messages'?'Your conversation':section==='notes'?'Shared project notes':'Your requests'}</h2>{items.filter(i=>i.kind===kinds[section]).slice().reverse().map(i=><article className="portal-record" key={i.id}><div><b>{i.title}</b><span>{i.author==='team'?'LayeredFX team':'You'} · {new Date(i.createdAt).toLocaleDateString()} · {i.status}</span><p>{i.body}</p>{i.date&&<small>Preferred date: {i.date}</small>}</div>{i.status==='requested'&&<button disabled={busy} onClick={()=>void save({type:'status',id:i.id,status:'cancelled'})}>Cancel request</button>}</article>)}{!items.some(i=>i.kind===kinds[section])&&<p>No {section==='messages'?'messages':section==='notes'?'notes':'requests'} yet.</p>}</section>}
 {section==='profile'&&<section className="portal-card portal-profile"><h2>Your details</h2><form key={`${account.user_id}:${account.revision}`} onSubmit={async e=>{e.preventDefault();const data=new FormData(e.currentTarget);await save({type:'profile',profile:Object.fromEntries(data)});}}>{Object.entries(account.state.profile).map(([key,value])=><label key={key}>{key[0].toUpperCase()+key.slice(1)}<input name={key} defaultValue={value} required={key==='name'} maxLength={key==='address'?500:key==='phone'?40:key==='name'?150:200}/></label>)}<p>Email: {account.email}</p><p>Account type: {account.kind}. Contact the team to request account changes.</p><button className="portal-primary" disabled={busy}>Save profile</button></form></section>}
 {section==='media'&&active&&<section className="portal-card"><h2>Your project, in pictures.</h2><p>Upload JPEG, PNG, WebP, MP4 or WebM files up to 20 MB. Media is private to your account and the LayeredFX team.</p><label className="portal-upload">{busy?'Uploading…':'Add photos or video'}<input type="file" disabled={busy} accept="image/jpeg,image/png,image/webp,video/mp4,video/webm" onChange={async e=>{const file=e.target.files?.[0];if(!file)return;e.target.value='';setBusy(true);setError('');try{if(!['image/jpeg','image/png','image/webp','video/mp4','video/webm'].includes(file.type))throw Error('Choose JPEG, PNG, WebP, MP4 or WebM.');if(account.state.media.length>=100)throw Error('Media limit reached.');if(file.size>20*1024*1024)throw Error('Choose a file under 20 MB.');let next:PortalAccount;if(demo){const id=crypto.randomUUID();await localMedia(id,file);next=structuredClone(account);next.state.media.push({id,name:file.name,type:file.type,path:id,size:file.size});next.revision++;localStorage.setItem(key,JSON.stringify(next));}else{const res=await fetch('/api/portal/media',{method:'POST',headers:{'Content-Type':file.type,'x-file-name':encodeURIComponent(file.name),'x-portal-revision':String(account.revision)},body:file});next=await res.json();if(!res.ok)throw Error((next as unknown as {message:string}).message);}setAccount(next);}catch(e){setError(e instanceof Error?e.message:'Upload failed.');}finally{setBusy(false);}}}/></label><div className="portal-media-grid">{account.state.media.map(file=><Media key={file.id} file={file} demo={demo}/>)}</div></section>}
 </main><footer className="portal-footer">LayeredFX · Beautiful work, thoughtfully organized.</footer></div></div>;
}
function Media({file,demo}:{file:PortalMedia;demo:boolean}){const[url,setUrl]=useState(''),[error,setError]=useState('');useEffect(()=>{let active=true,object='';(async()=>{try{if(demo){const blob=await localMedia(file.id);if(!blob)throw Error('This file is no longer on this device.');object=URL.createObjectURL(blob);if(active)setUrl(object);}else{const res=await fetch(`/api/portal/media?id=${file.id}`);const data=await res.json();if(!res.ok)throw Error(data.message);if(active)setUrl(data.url);}}catch(e){if(active)setError(e instanceof Error?e.message:'Media unavailable.');}})();return()=>{active=false;if(object)URL.revokeObjectURL(object);};},[file.id,demo]);return <article>{url&&(file.type.startsWith('video/')?<video controls src={url}/>:<Image src={url} alt={file.name} width={640} height={480} unoptimized/>)}<p>{file.name}</p>{error&&<small>{error}</small>}</article>;}
export function demoAccount(kind:PortalAccount['kind']):PortalAccount{return{user_id:'portal-demo',org_id:'local',email:'preview@example.test',kind,status:'active',revision:0,state:initialPortal(isPartner(kind)?'Sample Partner':'Sample Customer')};}
