"use client";
import Link from 'next/link';
import {useEffect,useState} from 'react';
import {PageTitle,Panel,Button,Field} from '@/components/operations/shared';
import {useOperations} from '@/components/operations/provider';
import type {PortalAccount} from '@/lib/portal/model';
export function PortalStaff(){const{mode,actor}=useOperations();const[accounts,setAccounts]=useState<PortalAccount[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function load(){try{const res=await fetch('/api/portal/staff');const data=await res.json();if(!res.ok)throw Error(data.message);setAccounts(data);}catch(e){setError(e instanceof Error?e.message:'Could not load accounts.');}}
 useEffect(()=>{if(mode!=='demo')void load();},[mode]);
 async function change(account:PortalAccount,command:Record<string,unknown>){setBusy(true);setError('');try{const res=await fetch('/api/portal/staff',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({userId:account.user_id,revision:account.revision,command})});const data=await res.json();if(!res.ok)throw Error(data.message);setAccounts(list=>list.map(a=>a.user_id===data.user_id?data:a));}catch(e){setError(e instanceof Error?e.message:'Save failed.');}finally{setBusy(false);}}
 return <><PageTitle title="Customer & partner portals" description="Approve partner access, review requests and reply to portal conversations."><Button variant="outline" onClick={()=>void load()}>Reload accounts</Button></PageTitle>{mode==='demo'&&<Panel title="Local portal previews"><p>Live portal accounts appear here after Supabase setup. Customer and partner previews store their records separately in this browser.</p><Link href="/portal">Open customer preview →</Link><br/><Link href="/partner">Open partner preview →</Link></Panel>}{error&&<p role="alert" className="ops-error">{error}</p>}{accounts.map(account=><Panel key={account.user_id} title={`${account.state.profile.name} · ${account.kind} · ${account.status}`}><p>{account.email} · {account.state.profile.company} · {account.state.profile.phone}</p>{actor.role==='admin'&&<div className="ops-actions"><Button disabled={busy||account.status==='active'} onClick={()=>void change(account,{type:'approval',status:'active'})}>Approve access</Button><Button variant="outline" disabled={busy||account.status==='suspended'} onClick={()=>void change(account,{type:'approval',status:'suspended'})}>Suspend access</Button></div>}{account.state.items.map(item=><article className="quick-note" key={item.id}><b>{item.title}</b><small>{item.kind} · {item.author} · {item.status} {item.date}</small><p>{item.body}</p>{!['note','message'].includes(item.kind)&&<div className="ops-actions">{['confirmed','declined','completed'].map(status=><Button size="sm" variant="outline" disabled={busy} key={status} onClick={()=>void change(account,{type:'status',id:item.id,status})}>{status}</Button>)}</div>}</article>)}{account.state.media.map(file=><div key={file.id}><Button variant="outline" onClick={async()=>{const res=await fetch(`/api/portal/media?account=${account.user_id}&id=${file.id}`);const data=await res.json();if(res.ok)window.open(data.url,'_blank','noopener,noreferrer');else setError(data.message);}}>View {file.name}</Button></div>)}{account.status==='active'&&<form onSubmit={async e=>{e.preventDefault();const form=e.currentTarget;const body=String(new FormData(form).get('reply'));await change(account,{type:'item',kind:'message',title:'Message from LayeredFX',body});}}><Field label="Reply to account"><textarea name="reply" required maxLength={4000}/></Field><Button disabled={busy}>Send portal reply</Button></form>}</Panel>)}{!accounts.length&&mode!=='demo'&&!error&&<p>No portal accounts yet.</p>}</>;
}
