// Adapted from Channel Cast lib/crm/deals.ts, pipeline-guidance.ts and stage-config.ts.
// Stable keys are retained; guidance and opportunity types are LayeredFX-specific.
export const PATH = ['new_working', 'contacted', 'qualified', 'opportunity', 'proposal', 'negotiation', 'closed_won'];
export const STAGES = [...PATH, 'closed_lost', 'nurture'];
export const OPEN = PATH.slice(0, -1);
export const LABELS = { new_working: 'New / Working', contacted: 'Contacted', qualified: 'Qualified', opportunity: 'Site Visit / Scope', proposal: 'Estimate / Proposal', negotiation: 'Negotiation', closed_won: 'Closed Won', closed_lost: 'Closed Lost', nurture: 'Nurture' };
export const SERVICES = ['Wall Wraps', 'Cabinet Wraps', 'Countertop Wraps', 'Appliance Wraps', 'Wallpaper', 'Roman Clay', 'Faux Concrete', 'Window Film', 'Interior Painting', 'Exterior Painting'];
export const TASK_STATUS = ['not_started', 'in_progress', 'waiting', 'blocked', 'complete'];
export const PRIORITIES = ['low', 'medium', 'high', 'urgent'];
export const LOST_REASONS = ['Price', 'No Budget', 'Timing', 'No Response', 'Competitor', 'Not a Fit', 'Project Canceled', 'Duplicate', 'Other'];
const item = (id, label, required = false, auto = null) => ({ id, label, required, auto });
export const DEFAULT_STAGES = {
    new_working: { label: LABELS.new_working, probability: 10, goal: 'Give every opportunity an owner, a verified contact, and a next action.', actions: ['Confirm contact details and lead source.', 'Make the first outreach.', 'Schedule a follow-up.'], items: [item('owner', 'Owner assigned', true, 'owner'), item('contact', 'Contact linked', true, 'contact'), item('source', 'Lead source confirmed', false, 'source'), item('outreach', 'First outreach attempted'), item('next', 'Next action scheduled', true, 'next')] },
    contacted: { label: LABELS.contacted, probability: 20, goal: 'Establish two-way contact and understand the desired transformation.', actions: ['Identify the surfaces and service.', 'Identify the decision-maker.', 'Book a consultation.'], items: [item('twoway', 'Two-way contact made', true), item('need', 'Project need identified', true), item('dm', 'Decision-maker identified'), item('followup', 'Follow-up scheduled', false, 'next')] },
    qualified: { label: LABELS.qualified, probability: 35, goal: 'Confirm fit, budget, authority, location and timing.', actions: ['Confirm residential or commercial scope.', 'Check installation requirements.', 'Confirm estimated budget and timing.'], items: [item('fit', 'Service and location fit confirmed', true), item('dm', 'Decision-maker identified', true), item('type', 'Project type selected', true, 'type'), item('value', 'Estimated value entered', true, 'value'), item('close', 'Expected close date entered', true, 'close'), item('next', 'Next action scheduled', false, 'next')] },
    opportunity: { label: LABELS.opportunity, probability: 50, goal: 'Document the surfaces, measurements, condition, and proposed finishes.', actions: ['Perform the site visit or photo assessment.', 'Record measurements and substrate condition.', 'Shortlist materials and finishes.'], items: [item('products', 'Services scoped', true, 'products'), item('measure', 'Measurements and surface condition recorded', true), item('stakeholders', 'Stakeholders mapped'), item('next', 'Next milestone agreed', false, 'next')] },
    proposal: { label: LABELS.proposal, probability: 65, goal: 'Deliver a clear estimate with scope, exclusions and next steps.', actions: ['Prepare the estimate and material selections.', 'Confirm the client received it.', 'Schedule the review.'], items: [item('created', 'Estimate / proposal created', true), item('sent', 'Estimate / proposal sent', true), item('reviewed', 'Pricing reviewed with client'), item('objections', 'Questions or objections recorded'), item('meeting', 'Review meeting scheduled', false, 'next')] },
    negotiation: { label: LABELS.negotiation, probability: 80, goal: 'Resolve price, scope, schedule and approval details.', actions: ['Agree final scope and pricing.', 'Confirm contract status and installation window.', 'Record deposit requirements without processing payment.'], items: [item('pricing', 'Final pricing agreed', true), item('contract', 'Contract status known', true), item('dates', 'Installation window discussed'), item('billing', 'Billing requirements captured'), item('decision', 'Decision date confirmed', false, 'close')] },
    closed_won: { label: LABELS.closed_won, probability: 100, goal: 'Preserve the sale and hand off into installation planning.', actions: ['Record the final value and won summary.', 'Confirm the client relationship.', 'Create an installation plan when ready.'], items: [item('value', 'Final value recorded', true, 'value'), item('closedate', 'Close date recorded', true, 'closed'), item('summary', 'Won summary recorded', false, 'summary'), item('role', 'Contact converted to client', false, 'client')] },
    closed_lost: { label: LABELS.closed_lost, probability: 0, goal: 'Record why the opportunity was lost without deleting its history.', actions: ['Select the lost reason.', 'Record competitor and useful context.', 'Reopen or nurture when appropriate.'], items: [item('reason', 'Lost reason recorded', true, 'lost'), item('notes', 'Lost notes captured')] },
    nurture: { label: LABELS.nurture, probability: 10, goal: 'Park the opportunity with a clear revisit date.', actions: ['Agree a follow-up date.', 'Keep the owner and previous history.'], items: [item('revisit', 'Revisit action and date scheduled', true, 'next')] }
};
export const DOC_TEMPLATES = [
    { id: 'blank', name: 'Blank document', category: 'General', description: 'A clean page for your ideas.', lines: [] },
    { id: 'consultation', name: 'Client consultation', category: 'Sales', description: 'Capture surfaces, goals, constraints and follow-up.', lines: ['# Client consultation', '## Project goals', 'Describe the desired transformation.', '## Surfaces and measurements', 'Record substrate, dimensions and condition.', '## Materials and finishes', 'Record sample codes and client preferences.', '## Constraints', 'Access, occupied spaces, timing and budget.', '## Next steps', 'Assign an owner and follow-up date.'] },
    { id: 'scope', name: 'Installation scope', category: 'Projects', description: 'Scope, preparation, exclusions and acceptance.', lines: ['# Installation scope', '## Included services', 'List the surfaces and services.', '## Preparation', 'Document protection, removal and preparation.', '## Materials', 'Record approved finishes and quantities.', '## Exclusions and assumptions', 'List items requiring separate approval.', '## Completion checklist', 'Record the final walkthrough and handoff.'] },
    { id: 'meeting', name: 'Team meeting', category: 'Team', description: 'Agenda, decisions and actions.', lines: ['# Team meeting', '## Agenda', '## Decisions', '## Actions', 'Owner · Action · Due date'] },
    { id: 'handoff', name: 'Project handoff', category: 'Projects', description: 'Move from a won opportunity to installation.', lines: ['# Project handoff', '## Client and opportunity', '## Approved scope', '## Material selections', '## Installation schedule', '## Risks and access', '## Assigned team', '## Client communication'] }
];
export const PLAN_TEMPLATES = [
    { id: 'blank', name: 'Blank plan', description: 'Build your own groups and tasks.', groups: ['To plan', 'In progress', 'Complete'], tasks: [] },
    { id: 'surface', name: 'Surface transformation', description: 'From site survey through client walkthrough.', groups: ['Survey & scope', 'Materials & approval', 'Installation', 'Handoff'], tasks: [['Survey & scope', 'Measure surfaces and document condition', 1, ['Record dimensions', 'Take before photos']], ['Materials & approval', 'Confirm finish samples with client', 3, ['Record finish code', 'Record approval']], ['Materials & approval', 'Confirm availability and order materials', 5, []], ['Installation', 'Protect the space and prepare surfaces', 8, []], ['Installation', 'Install approved finish', 9, []], ['Handoff', 'Client walkthrough and care instructions', 10, ['Resolve punch list', 'Take after photos']]] },
    { id: 'painting', name: 'Interior / exterior painting', description: 'Preparation, application, inspection and handoff.', groups: ['Assessment', 'Preparation', 'Application', 'Closeout'], tasks: [['Assessment', 'Confirm colors, surfaces and access', 1, []], ['Preparation', 'Protection, repairs and substrate preparation', 3, []], ['Application', 'Apply approved coating system', 5, []], ['Closeout', 'Inspect finish and complete walkthrough', 7, []]] },
    { id: 'commercial', name: 'Commercial installation', description: 'Coordinate access, approvals and occupied-space work.', groups: ['Coordination', 'Approvals', 'Delivery', 'Handoff'], tasks: [['Coordination', 'Confirm site contact and access requirements', 1, []], ['Approvals', 'Confirm drawings, materials and work window', 3, []], ['Delivery', 'Coordinate installation team', 6, []], ['Handoff', 'Complete punch list and closeout documents', 10, []]] }
];
