"use client";
import {BrandedSelect,BrandedInput} from './branded-fields';
// Source-reviewed adaptation of Channel Cast components/crm/contacts-page.tsx.
import {useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
import {useRouter} from 'next/navigation';
import {Download,Plus,Smartphone,Upload,Phone,MessageSquare} from 'lucide-react';
import {useOperations} from './provider';
import {Button,Calendar,Field,Modal,PageTitle,SearchBox,Views} from './shared';
import type {Contact} from '@/lib/operations/types';
import {contactsCsv,parseContactFile,pickedDraft,reviewCandidates,type Candidate,type Draft} from '@/lib/contacts/import';
import {contactPickerSupported,contactsManager} from '@/lib/channelcast/phone-import';
import {openQuickTool} from './quick-events';
const categories:Record<string,string>={contact:'Contact',lead:'Lead',prospect:'Potential customer',client:'Customer'};
const blank:Draft={name:'',email:'',phone:'',company:'',type:'contact',status:'active',source:'Manual',tags:[]};
function download(content:string){const url=URL.createObjectURL(new Blob([content],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='layeredfx-contacts.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export function ContactsPage({initialTab='all'}:{initialTab?:string}){
 const {state,actor,dispatch,busy}=useOperations();const router=useRouter();const readonly=actor.role==='viewer';
 const [tab,setTab]=useState(initialTab),[query,setQuery]=useState(''),[status,setStatus]=useState('active'),[tag,setTag]=useState(''),[view,setView]=useState('List');
 const [selected,setSelected]=useState<string|null>(null),[edit,setEdit]=useState<Partial<Contact>|null>(null),[importOpen,setImportOpen]=useState(false),[checked,setChecked]=useState<string[]>([]),[bulkOwner,setBulkOwner]=useState('');
 const [activity,setActivity]=useState(''),[kind,setKind]=useState('note'),[userId,setUserId]=useState('');
 const contact=state.contacts.find(c=>c.id===selected);const active=state.contacts.filter(c=>c.status!=='archived');
 const rows=state.contacts.filter(c=>(tab==='all'||(tab==='users'?!!c.userId:c.type===tab))&&(!status||(c.status||'active')===status)&&(!tag||c.tags?.includes(tag))&&[c.name,c.email,c.phone,c.company].join(' ').toLowerCase().includes(query.toLowerCase()));
 useEffect(()=>{const params=new URLSearchParams(location.search);if(params.get('import')==='phone')setImportOpen(true);},[]);
 const openContact=(c:Contact)=>{setSelected(c.id);setUserId(c.userId||'');setActivity('');};
 const pipeline=async(id:string)=>{const result=await dispatch({type:'contact.pipeline',id});if(result)router.push(`/admin/pipeline/${result}`);};
 const toggle=(id:string)=>setChecked(prev=>prev.includes(id)?prev.filter(x=>x!==id):[...prev,id]);
 async function bulk(action:string){for(const id of checked){const result=await dispatch(action==='pipeline'?{type:'contact.pipeline',id}:action==='lead'?{type:'contact.lead',id}:{type:'contact.save',id,patch:action==='owner'?{owner:bulkOwner}:{status:'archived'}});if(!result)return;}setChecked([]);}
 const tile=(c:Contact)=><button className="contact-tile" onClick={()=>openContact(c)}><span className="contact-avatar">{c.name.slice(0,2).toUpperCase()}</span><span><b>{c.name}</b><small>{c.company||c.email||c.phone||'No contact details yet'}</small></span><span className="contact-chip">{categories[c.type]||'Contact'}</span></button>;
 return <><PageTitle title={initialTab==='lead'?'Leads':'Contacts'} description="Contacts, leads, potential customers and clients — one connected relationship."><Button variant="outline" onClick={()=>setImportOpen(true)} disabled={readonly}><Smartphone size={16}/> From phone</Button><Button variant="outline" onClick={()=>setImportOpen(true)} disabled={readonly}><Upload size={16}/> Import</Button><Button variant="outline" onClick={()=>download(contactsCsv(rows))}><Download size={16}/> Export</Button><Button onClick={()=>setEdit({...blank,owner:actor.id})} disabled={readonly}><Plus size={16}/> Add contact</Button></PageTitle>
 <div className="ops-stats">{[['Total',active.length],['Customers',active.filter(c=>c.type==='client').length],['Leads',active.filter(c=>c.type==='lead').length],['Companies',new Set(active.map(c=>c.company).filter(Boolean)).size]].map(([label,count])=><div key={label}><span>{label}</span><b>{count}</b></div>)}</div>
 <div className="contact-tabs">{[['all','All'],['contact','Contacts'],['lead','Leads'],['prospect','Potential customers'],['client','Customers'],['users','Linked users']].map(([id,label])=><button key={id} aria-pressed={tab===id} onClick={()=>setTab(id)}>{label} <small>{active.filter(c=>id==='all'||(id==='users'?!!c.userId:c.type===id)).length}</small></button>)}</div>
 <div className="ops-toolbar contact-toolbar"><SearchBox value={query} onChange={setQuery} placeholder="Search name, company, email or phone"/><BrandedSelect aria-label="Contact tag" value={tag} onChange={e=>setTag(e.target.value)}><option value="">All tags</option>{[...new Set(active.flatMap(c=>c.tags||[]))].map(t=><option key={t}>{t}</option>)}</BrandedSelect><BrandedSelect aria-label="Contact status" value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option><option value="active">Active</option><option value="inactive">Inactive</option><option value="archived">Archived</option></BrandedSelect><Views values={['List','Table','Cards','Kanban','Calendar']} value={view} onChange={setView}/></div>
 {!readonly&&<div className="contact-bulk"><label><BrandedInput type="checkbox" aria-label="Select visible contacts" checked={rows.length>0&&rows.every(c=>checked.includes(c.id))} onChange={e=>setChecked(e.target.checked?rows.map(c=>c.id):[])}/> Select visible ({checked.length})</label>{checked.length>0&&<><Button size="sm" disabled={busy} onClick={()=>void bulk('pipeline')}>Add to Pipeline</Button><Button size="sm" variant="outline" disabled={busy} onClick={()=>void bulk('lead')}>Work leads</Button><BrandedSelect aria-label="Bulk owner" value={bulkOwner} onChange={e=>setBulkOwner(e.target.value)}><option value="">Choose owner</option>{state.people.filter(p=>p.role!=='viewer').map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</BrandedSelect><Button size="sm" variant="outline" disabled={busy||!bulkOwner} onClick={()=>void bulk('owner')}>Assign owner</Button><Button size="sm" variant="outline" disabled={busy} onClick={()=>{if(confirm('Archive the selected contacts? Their history will be kept.'))void bulk('archive');}}>Archive</Button></>}</div>}
 {view==='List'&&<div className="contact-list">{rows.map(c=><div className="contact-list-row" key={c.id}>{!readonly&&<BrandedInput type="checkbox" aria-label={`Select ${c.name}`} checked={checked.includes(c.id)} onChange={()=>toggle(c.id)}/>} {tile(c)}<span className="contact-list-meta">{c.tags?.join(' · ')}</span></div>)}</div>}
 {view==='Table'&&<div className="contact-table-wrap"><table className="contact-table"><thead><tr>{['Name','Company','Email','Phone','Category','Owner'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map(c=><tr key={c.id}><td><button onClick={()=>openContact(c)}>{c.name}</button></td><td>{c.company}</td><td>{c.email}</td><td>{c.phone}</td><td>{categories[c.type]}</td><td>{state.people.find(p=>p.id===c.owner)?.name||'Unassigned'}</td></tr>)}</tbody></table></div>}
 {view==='Cards'&&<div className="contact-cards">{rows.map(c=><article key={c.id}>{tile(c)}<p>{c.email}</p><p>{c.phone}</p><small>{c.tags?.join(' · ')}</small></article>)}</div>}
 {view==='Kanban'&&<div className="contact-kanban">{Object.entries(categories).map(([type,label])=><section key={type} onDragOver={e=>{if(!readonly)e.preventDefault();}} onDrop={e=>{e.preventDefault();const id=e.dataTransfer.getData('text/plain');if(rows.some(c=>c.id===id))void dispatch({type:'contact.save',id,patch:{type}});}}><h2>{label} <small>{rows.filter(c=>c.type===type).length}</small></h2>{rows.filter(c=>c.type===type).map(c=><article key={c.id} draggable={!readonly&&c.status!=='archived'} onDragStart={e=>e.dataTransfer.setData('text/plain',c.id)}>{tile(c)}</article>)}</section>)}</div>}
 {view==='Calendar'&&<Calendar records={rows.map(c=>({id:c.id,title:c.name,date:c.lastContact||'',onClick:()=>openContact(c)}))}/>}
 {!rows.length&&<p className="contact-empty">No contacts match this view. Add a contact or import a file to get started.</p>}
 <Modal title={contact?.name||'Contact'} description="The contact identity stays linked across leads, pipeline and customers." open={!!contact} onClose={()=>setSelected(null)}>{contact&&<>
 <div className="contact-detail-actions"><Button disabled={readonly||busy||contact.status==='archived'} onClick={()=>void pipeline(contact.id)}>Add to Pipeline</Button><Button variant="outline" disabled={readonly||busy||contact.status==='archived'} onClick={()=>void dispatch({type:'contact.lead',id:contact.id})}>Work Lead</Button><Button variant="outline" onClick={()=>{setSelected(null);openQuickTool('dialpad',{phone:contact.phone,contactId:contact.id});}} disabled={!contact.phone}><Phone size={16}/> Call</Button><Button variant="outline" onClick={()=>{setSelected(null);openQuickTool('sms',{phone:contact.sms||contact.phone,contactId:contact.id});}} disabled={!contact.phone&&!contact.sms}><MessageSquare size={16}/> Text</Button>{contact.email&&<a href={`mailto:${encodeURIComponent(contact.email)}`}>Email</a>}<Button variant="outline" disabled={readonly} onClick={()=>setEdit(contact)}>Edit</Button></div>
 <div className="contact-detail-grid">{[['Email',contact.email],['Phone',contact.phone],['Company',contact.company],['Source',contact.source],['Owner',state.people.find(p=>p.id===contact.owner)?.name],['Location',[contact.city,contact.state].filter(Boolean).join(', ')],['Category',categories[contact.type]],['Status',contact.status||'active']].map(([label,value])=><div key={label}><small>{label}</small><p>{value||'—'}</p></div>)}</div>
 {contact.notes&&<p className="contact-notes">{contact.notes}</p>}
 <div className="contact-detail-actions">{state.leads.filter(l=>l.contactId===contact.id).map(l=><Link key={l.id} href="/admin/leads">Lead: {l.name}</Link>)}{state.deals.filter(d=>d.contactId===contact.id).map(d=><Link key={d.id} href={`/admin/pipeline/${d.id}`}>Opportunity: {d.name}</Link>)}</div>
 <Field label="Linked user"><BrandedSelect value={userId} onChange={e=>setUserId(e.target.value)} disabled={actor.role!=='admin'}><option value="">No linked user</option>{state.people.map(p=><option key={p.id} value={p.id}>{p.name} ({p.role})</option>)}</BrandedSelect></Field><p className="ops-muted">Link an existing account. Contact imports never create logins or grant permissions.</p>{actor.role==='admin'&&<Button variant="outline" disabled={busy||contact.status==='archived'} onClick={()=>void dispatch({type:'contact.linkUser',id:contact.id,userId})}>Save user link</Button>}
 <h3>Activity &amp; communications</h3><Field label="Activity type"><BrandedSelect value={kind} onChange={e=>setKind(e.target.value)}>{['note','call','sms','email','meeting'].map(v=><option key={v}>{v}</option>)}</BrandedSelect></Field><Field label="Activity text"><textarea value={activity} onChange={e=>setActivity(e.target.value)} maxLength={5000}/></Field><Button disabled={readonly||busy||!activity.trim()||contact.status==='archived'} onClick={async()=>{if(await dispatch({type:'contact.activity',id:contact.id,kind,body:activity}))setActivity('');}}>Log activity</Button><small className="ops-muted">Manual activity logs do not send messages or place calls.</small>
 <div className="contact-timeline">{(state.contactActivities||[]).filter(a=>a.contactId===contact.id).slice().reverse().map(a=><article key={a.id}><b>{a.kind}</b><small>{new Date(a.occurredAt).toLocaleString()} · {state.people.find(p=>p.id===a.actorId)?.name}</small><p>{a.body}</p></article>)}</div>
 <div className="contact-detail-actions"><Button variant="outline" disabled={readonly||busy} onClick={()=>void dispatch({type:'contact.save',id:contact.id,patch:{status:contact.status==='archived'?'active':'archived'}})}>{contact.status==='archived'?'Restore':'Archive'}</Button><Button variant="outline" disabled={readonly||busy} onClick={async()=>{if(confirm('Delete this contact? Linked records or activity will prevent deletion.'))if(await dispatch({type:'contact.delete',id:contact.id}))setSelected(null);}}>Delete</Button></div>
 </>}</Modal>
 {edit&&<ContactEditor contact={edit} onClose={()=>setEdit(null)} onSaved={id=>{setEdit(null);setSelected(id);}}/>}
 {importOpen&&<ContactImporter onClose={()=>setImportOpen(false)}/>}
 </>;
}
function ContactEditor({contact,onClose,onSaved}:{contact:Partial<Contact>;onClose:()=>void;onSaved:(id:string)=>void}){
 const {state,actor,dispatch,busy}=useOperations();const [draft,setDraft]=useState({...blank,...contact}),[tags,setTags]=useState((contact.tags||[]).join(', '));
 const change=(key:string,value:string)=>setDraft(d=>({...d,[key]:value}));
 return <Modal title={contact.id?'Edit contact':'Add contact'} open onClose={onClose}><form onSubmit={async e=>{e.preventDefault();const id=await dispatch({type:'contact.save',id:contact.id,patch:{...draft,tags:tags.split(',').map(t=>t.trim()).filter(Boolean)}});if(id)onSaved(id);}}><div className="contact-editor-grid">{[['name','Full name'],['company','Company'],['email','Email'],['phone','Phone'],['title','Job title'],['source','Source'],['city','City'],['state','State'],['address','Address'],['zip','ZIP / postal code'],['website','Website']].map(([key,label])=><Field label={label} key={key}><BrandedInput type={key==='email'?'email':'text'} required={key==='name'} value={String(draft[key as keyof typeof draft]||'')} onChange={e=>change(key,e.target.value)}/></Field>)}<Field label="Category"><BrandedSelect value={draft.type} onChange={e=>change('type',e.target.value)}>{Object.entries(categories).map(([id,label])=><option key={id} value={id}>{label}</option>)}</BrandedSelect></Field><Field label="Owner"><BrandedSelect value={draft.owner||actor.id} onChange={e=>change('owner',e.target.value)}>{state.people.filter(p=>p.role!=='viewer').map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</BrandedSelect></Field><Field label="Last contact date"><BrandedInput type="date" value={draft.lastContact||''} onChange={e=>change('lastContact',e.target.value)}/></Field></div><Field label="Tags (comma separated)"><BrandedInput value={tags} onChange={e=>setTags(e.target.value)}/></Field><Field label="Notes"><textarea value={draft.notes||''} onChange={e=>change('notes',e.target.value)} maxLength={5000}/></Field><Button type="submit" disabled={busy}>Save contact</Button></form></Modal>;
}
function ContactImporter({onClose}:{onClose:()=>void}){
 const {state,actor,dispatch,busy}=useOperations();const [drafts,setDrafts]=useState<Draft[]>([]),[selected,setSelected]=useState<number[]>([]),[error,setError]=useState(''),[type,setType]=useState('contact'),[importing,setImporting]=useState(false),[progress,setProgress]=useState('');
 const candidates=useMemo(()=>reviewCandidates(drafts,state.contacts),[drafts,state.contacts]);
 const [picker,setPicker]=useState(false);useEffect(()=>setPicker(contactPickerSupported()&&window.isSecureContext),[]);
 function review(next:Draft[]){if(!next.length)throw new Error('No contacts found in this selection.');if(next.length>5000)throw new Error('Split the file into batches of at most 5,000 contacts.');setDrafts(next);setSelected(reviewCandidates(next,state.contacts).filter(c=>!c.match&&!c.conflict&&!c.batchDuplicate).map(c=>c.key));setProgress('');}
 const blocked=(c:Candidate)=>c.conflict||c.batchDuplicate||c.match?.status==='archived';
 async function fromPhone(){try{setError('');const manager=contactsManager();if(!manager)throw new Error('Use a VCF file on this browser.');const results=await manager.select(['name','email','tel'],{multiple:true});if(results.length)review(results.map(pickedDraft));}catch(e){if(e instanceof Error&&e.name!=='AbortError')setError(e.message);}}
 async function importSelected(){setImporting(true);setError('');const selectedRows=candidates.filter(c=>selected.includes(c.key)&&!blocked(c));let done=0;try{
  while(done<selectedRows.length){const batch:typeof selectedRows=[];let bytes=0;while(done+batch.length<selectedRows.length&&batch.length<200){const candidate=selectedRows[done+batch.length];const size=new TextEncoder().encode(JSON.stringify(candidate.draft)).length+200;if(size>400000)throw new Error(`Contact ${candidate.draft.name} is too large. Remove unnecessary imported details.`);if(bytes+size>400000)break;batch.push(candidate);bytes+=size;}
   const rows=batch.map(c=>({draft:{...c.draft,type,owner:actor.id},mergeId:c.match?.id}));setProgress(`Saving ${done+1}–${done+batch.length} of ${selectedRows.length}…`);
   if(!await dispatch({type:'contact.import',rows})){setProgress(`Import stopped after ${done} contacts. Remaining contacts are still selected. Review the error before retrying.`);return;}
   done+=batch.length;setSelected(prev=>prev.filter(k=>!batch.some(c=>c.key===k)));
  }setProgress(`${done} contacts imported.`);onClose();
 }catch(e){setError(e instanceof Error?e.message:'Import failed.');}finally{setImporting(false);}}
 return <Modal title="Import contacts" description="Choose people, review matches, then save. Nothing is imported automatically." open onClose={()=>{if(!importing)onClose();}}>
 <div className="contact-detail-actions"><Button disabled={!picker||busy} onClick={()=>void fromPhone()}><Smartphone size={16}/> Choose from Android phone</Button><label className="contact-file"><Upload size={16}/> Choose .vcf or .csv<BrandedInput aria-label="Contact import file" type="file" accept=".vcf,.csv,text/vcard,text/csv" onChange={async e=>{const file=e.target.files?.[0];if(!file)return;try{setError('');if(file.size>2_000_000)throw new Error('Choose a file smaller than 2 MB.');review(parseContactFile(await file.text(),file.name));}catch(err){setError(err instanceof Error?err.message:'Could not read the file.');}e.target.value='';}}/></label></div>
 {!picker&&<p className="ops-muted">On Android, open the secure LayeredFX site in a browser with Contact Picker support. Alternatively, export contacts from your Android Contacts app as a .vcf file, transfer it here and select it above. Localhost on this computer is not a phone-accessible address.</p>}
 {error&&<p role="alert" className="ops-error">{error}</p>}{!!drafts.length&&<><Field label="Imported category"><BrandedSelect value={type} onChange={e=>setType(e.target.value)}>{Object.entries(categories).map(([id,label])=><option key={id} value={id}>{label}</option>)}</BrandedSelect></Field><p>{candidates.length} reviewed · {selected.length} selected. Large imports are saved in batches. Existing contacts are unchecked; selecting a match only fills blank fields.</p><div className="contact-detail-actions"><Button variant="outline" disabled={busy||importing} onClick={()=>setSelected(candidates.filter(c=>!blocked(c)).map(c=>c.key))}>Select all contacts</Button><Button variant="outline" disabled={busy||importing} onClick={()=>setSelected([])}>Deselect all</Button></div><div className="contact-import-list">{candidates.map(c=><label key={c.key}><BrandedInput type="checkbox" disabled={blocked(c)||busy||importing} checked={selected.includes(c.key)} onChange={e=>setSelected(prev=>e.target.checked?[...prev,c.key]:prev.filter(k=>k!==c.key))}/><span><b>{c.draft.name}</b><small>{c.draft.email||c.draft.phone}</small><small>{c.conflict?'Conflicting email / phone — resolve first':c.batchDuplicate?'Duplicate within this file — skipped':c.match?`Match: ${c.match.name}${c.match.status==='archived'?' (archived — restore first)':' — fill blank fields only'}`:'New contact'}</small></span></label>)}</div><Button disabled={busy||importing||!selected.length} onClick={()=>void importSelected()}>Import {selected.length} selected contacts</Button></>}
 {progress&&<p role="status">{progress}</p>}</Modal>;
}
