"use client";
// Adapted interaction layout from Channel Cast components/fab/fab.tsx.
import {useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import * as Dialog from '@radix-ui/react-dialog';
import type {Call,Device} from '@twilio/voice-sdk';
import {Plus,X,Sparkles,MessageCircle,MessageSquare,Phone,PhoneCall,StickyNote,Mic,Maximize2,Minimize2} from 'lucide-react';
import {useOperations} from './provider';
import {Button,Field} from './shared';
import type {QuickSeed,QuickTool} from './quick-events';
import {VoiceRecorder} from './voice-recorder';
const tools:{id:QuickTool;label:string;icon:typeof Plus}[]=[{id:'agent',label:'AI Agents',icon:Sparkles},{id:'dm',label:'Direct messages',icon:MessageCircle},{id:'sms',label:'SMS',icon:MessageSquare},{id:'dialpad',label:'Dialpad',icon:Phone},{id:'calls',label:'Call history',icon:PhoneCall},{id:'notes',label:'Notes',icon:StickyNote},{id:'record',label:'Recordings / Microphone',icon:Mic}];
type Capabilities={voice:boolean;sms:boolean;from:string;canSend:boolean};
const unavailable:Capabilities={voice:false,sms:false,from:'',canSend:false};
async function request(path:string,body?:unknown){const response=await fetch(`/api/communications/${path}`,{method:body===undefined?'GET':'POST',headers:body===undefined?{}:{'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body),cache:'no-store'});const data=await response.json();if(!response.ok)throw new Error(data.message||'Communication request failed.');return data;}
export function QuickActions(){
 const{mode}=useOperations();const[open,setOpen]=useState(false),[tool,setTool]=useState<QuickTool>('agent'),[expanded,setExpanded]=useState(false),[seed,setSeed]=useState<QuickSeed>({}),[caps,setCaps]=useState(unavailable),[configError,setConfigError]=useState('');
 useEffect(()=>{const listener=(event:Event)=>{const detail=(event as CustomEvent<QuickSeed&{tool:QuickTool}>).detail;if(tools.some(t=>t.id===detail.tool)){setTool(detail.tool);setSeed(detail);setOpen(true);}};window.addEventListener('lfx:quick-tool',listener);return()=>window.removeEventListener('lfx:quick-tool',listener);},[]);
 useEffect(()=>{if(mode==='supabase')void request('capabilities').then(setCaps).catch(e=>setConfigError(e.message));},[mode]);
 return <Dialog.Root open={open} onOpenChange={setOpen} modal={false}><Dialog.Trigger asChild><button className="ops-fab" aria-label="Quick actions" aria-expanded={open}>{open?<X/>:<Plus/>}</button></Dialog.Trigger><Dialog.Portal forceMount container={typeof document==='undefined'?undefined:document.querySelector('.ops')}><Dialog.Content forceMount hidden={!open} className={`ops-fab-panel ${expanded?'is-expanded':''}`} onInteractOutside={e=>e.preventDefault()} onEscapeKeyDown={e=>{if(expanded){e.preventDefault();setExpanded(false);}}}>
 <Dialog.Title className="sr-only">Quick actions</Dialog.Title><Dialog.Description className="sr-only">Agents, direct messages, SMS, voice calls, notes and microphone recordings.</Dialog.Description><header className="ops-fab-header"><div role="tablist" aria-label="Quick tools">{tools.map(t=>{const Icon=t.icon;return <button key={t.id} role="tab" aria-selected={tool===t.id} aria-controls={`quick-${t.id}`} id={`quick-tab-${t.id}`} tabIndex={tool===t.id?0:-1} title={t.label} aria-label={t.label} onKeyDown={e=>{if(['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();const i=(tools.findIndex(t=>t.id===tool)+(e.key==='ArrowRight'?1:-1)+tools.length)%tools.length;setTool(tools[i].id);document.getElementById(`quick-tab-${tools[i].id}`)?.focus();}}} onClick={()=>setTool(t.id)}><Icon size={19}/></button>;})}</div><button aria-label={expanded?'Minimize quick actions':'Expand quick actions'} onClick={()=>setExpanded(v=>!v)}>{expanded?<Minimize2 size={17}/>:<Maximize2 size={17}/>}</button><Dialog.Close aria-label="Close quick actions"><X size={19}/></Dialog.Close></header>
 <div className="ops-fab-body">{configError&&<p className="ops-error">{configError}</p>}{tools.map(t=><section role="tabpanel" aria-labelledby={`quick-tab-${t.id}`} id={`quick-${t.id}`} key={t.id} hidden={tool!==t.id}>
 {t.id==='agent'&&<div className="quick-tool"><h2>AI Agents</h2><p>Open your agent workspace to review skills and conversations.</p><Button asChild><Link href="/admin/agent" onClick={()=>setOpen(false)}>Open AI Agents</Link></Button><p className="ops-muted">Agent execution still requires the LayeredFX AI provider integration.</p></div>}
 {t.id==='dm'&&<DirectMessages/>}{t.id==='notes'&&<QuickNotes/>}{t.id==='sms'&&<SmsTool caps={caps} seed={seed}/>}{t.id==='dialpad'&&<Dialpad caps={caps} seed={seed}/>}{t.id==='calls'&&<CallHistory caps={caps} active={open&&tool==='calls'} onCall={phone=>{setSeed({phone});setTool('dialpad');}}/>}{t.id==='record'&&<VoiceRecorder/>}
 </section>)}</div></Dialog.Content></Dialog.Portal></Dialog.Root>;
}
function DirectMessages(){const{state,actor,dispatch,busy,mode}=useOperations();const[recipient,setRecipient]=useState(''),[body,setBody]=useState('');const messages=(state.directMessages||[]).filter(m=>(m.senderId===actor.id&&m.recipientId===recipient)||(m.senderId===recipient&&m.recipientId===actor.id));return <div className="quick-tool"><h2>Direct messages</h2><p>{mode==='demo'?'Local preview conversation. No message leaves this browser.':'Messages are shared with the selected LayeredFX team member. Reload to receive new messages.'}</p><Field label="Recipient"><select value={recipient} onChange={e=>setRecipient(e.target.value)}><option value="">Choose a team member</option>{state.people.filter(p=>p.id!==actor.id).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></Field><div className="quick-messages">{messages.map(m=><article className={m.senderId===actor.id?'is-own':''} key={m.id}><small>{state.people.find(p=>p.id===m.senderId)?.name} · {new Date(m.createdAt).toLocaleString()}</small><p>{m.body}</p></article>)}{!messages.length&&<p>No messages yet.</p>}</div><Field label="Message"><textarea value={body} onChange={e=>setBody(e.target.value)} maxLength={4000}/></Field><Button disabled={busy||actor.role==='viewer'||!recipient||!body.trim()} onClick={async()=>{if(await dispatch({type:'message.send',recipientId:recipient,body}))setBody('');}}>{mode==='demo'?'Save preview message':'Send direct message'}</Button></div>;}
function QuickNotes(){const{state,dispatch,busy}=useOperations();const[id,setId]=useState<string|undefined>(),[base,setBase]=useState<number|undefined>(),[title,setTitle]=useState(''),[body,setBody]=useState('');return <div className="quick-tool"><h2>Private notes</h2><Field label="Title"><input value={title} onChange={e=>setTitle(e.target.value)} maxLength={150}/></Field><Field label="Note"><textarea value={body} onChange={e=>setBody(e.target.value)} maxLength={10000} rows={6}/></Field><Button disabled={busy||!title.trim()||!body.trim()} onClick={async()=>{if(await dispatch({type:'note.save',id,expectedRevision:base,title,body})){setId(undefined);setBase(undefined);setTitle('');setBody('');}}}>Save note</Button><Button variant="outline" onClick={()=>{if((title||body)&&!confirm('Discard unsaved note changes?'))return;setId(undefined);setBase(undefined);setTitle('');setBody('');}}>New note</Button>{(state.quickNotes||[]).slice().reverse().map(n=><article className="quick-note" key={n.id}><button onClick={()=>{if((title||body)&&!confirm('Replace unsaved note changes?'))return;setId(n.id);setBase(n.revision||0);setTitle(n.title);setBody(n.body);}}><b>{n.title}</b><small>{new Date(n.updatedAt).toLocaleString()}</small></button><p>{n.body}</p><button disabled={busy} onClick={()=>{if(confirm('Delete this private note?'))void dispatch({type:'note.delete',id:n.id});}}>Delete note</button></article>)}</div>;}
function SmsTool({caps,seed}:{caps:Capabilities;seed:QuickSeed}){const[to,setTo]=useState(seed.phone||''),[body,setBody]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[history,setHistory]=useState<{id:string;body:string;status:string}[]>([]);useEffect(()=>{if(seed.phone)setTo(seed.phone);},[seed]);return <div className="quick-tool"><h2>SMS</h2><p>{caps.sms?`From ${caps.from}`:'Connect your LayeredFX Twilio account to send SMS. Drafting is available now.'}</p><Field label="SMS phone number"><input type="tel" placeholder="+14805550123" value={to} onChange={e=>setTo(e.target.value)}/></Field><Field label="SMS message"><textarea value={body} onChange={e=>setBody(e.target.value)} maxLength={1600}/></Field><Button disabled={!caps.sms||!caps.canSend||busy||!to||!body.trim()} onClick={async()=>{setBusy(true);try{const result=await request('sms',{to,body});setMessage(result.message);setBody('');}catch(e){setMessage(e instanceof Error?e.message:'Send failed.');}finally{setBusy(false);}}}>Send SMS</Button><Button variant="outline" disabled={!caps.sms||busy||!to} onClick={async()=>{try{setHistory((await request(`sms?to=${encodeURIComponent(to)}`)).messages);}catch(e){setMessage(e instanceof Error?e.message:'History failed.');}}}>Refresh sent history</Button>{message&&<p role="status">{message}</p>}{history.map(m=><article className="quick-note" key={m.id}><small>{m.status}</small><p>{m.body}</p></article>)}</div>;}
function Dialpad({caps,seed}:{caps:Capabilities;seed:QuickSeed}){
 const[number,setNumber]=useState(seed.phone||''),[status,setStatus]=useState('Ready'),[active,setActive]=useState(false),[muted,setMuted]=useState(false),[connecting,setConnecting]=useState(false);
 const device=useRef<Device|null>(null),call=useRef<Call|null>(null),mounted=useRef(true),attempt=useRef(false);
 useEffect(()=>{if(seed.phone)setNumber(seed.phone);},[seed]);useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;device.current?.destroy();};},[]);
 async function dial(){if(attempt.current)return;attempt.current=true;setConnecting(true);setStatus('Connecting…');try{
  const token=await request('token',{});const{Device}=await import('@twilio/voice-sdk');if(!mounted.current)return;device.current?.destroy();const client=new Device(token.token);device.current=client;client.on('error',(e:Error)=>setStatus(e.message));client.on('tokenWillExpire',()=>{void request('token',{}).then(t=>client.updateToken(t.token)).catch(e=>setStatus(e.message));});
  const connection=await client.connect({params:{To:number}});if(!mounted.current){connection.disconnect();return;}call.current=connection;setActive(true);setStatus('Calling…');setMuted(false);
  connection.on('accept',()=>setStatus('Call connected'));connection.on('disconnect',()=>{setActive(false);setStatus('Call ended');call.current=null;});connection.on('cancel',()=>{setActive(false);setStatus('Call cancelled');});connection.on('error',(e:Error)=>{setActive(false);setStatus(e.message);});
 }catch(e){setStatus(e instanceof Error?e.message:'Call failed.');}finally{attempt.current=false;if(mounted.current)setConnecting(false);}}
 return <div className="quick-tool"><h2>Dialpad</h2><Field label="Call from"><select disabled><option>{caps.from||'Twilio number not connected'}</option></select></Field><Field label="Phone number"><input type="tel" placeholder="+14805550123" value={number} onChange={e=>setNumber(e.target.value)} disabled={active||connecting}/></Field><div className="quick-dialpad">{'123456789*0#'.split('').map(d=><button key={d} onClick={()=>{if(active)call.current?.sendDigits(d);else setNumber(n=>n+d);}}>{d}</button>)}</div><div className="contact-detail-actions">{active?<><Button onClick={()=>call.current?.disconnect()}>End call</Button><Button variant="outline" onClick={()=>{call.current?.mute(!muted);setMuted(!muted);}}>{muted?'Unmute':'Mute'}</Button></>:<Button disabled={!caps.voice||!caps.canSend||connecting||!/^\+[1-9]\d{7,14}$/.test(number)} onClick={()=>void dial()}>{connecting?'Connecting…':'Call with Twilio'}</Button>}<Button variant="outline" disabled={active||connecting} onClick={()=>setNumber(n=>n.slice(0,-1))}>Backspace</Button></div><p role="status">{status}</p>{!caps.voice&&<p className="ops-muted">Twilio Voice is not connected. The call button becomes available after the server credentials and signed voice webhook are configured.</p>}<small>Calls are not recorded automatically. An active call continues when this panel is closed.</small></div>;
}
function CallHistory({caps,active,onCall}:{caps:Capabilities;active:boolean;onCall:(phone:string)=>void}){const[calls,setCalls]=useState<{id:string;to:string;status:string;at:string;duration:string}[]>([]),[error,setError]=useState('');async function load(){try{setCalls((await request('calls')).calls);setError('');}catch(e){setError(e instanceof Error?e.message:'Could not load call history.');}}useEffect(()=>{if(active&&caps.voice)void request('calls').then(data=>setCalls(data.calls)).catch(e=>setError(e.message));},[active,caps.voice]);return <div className="quick-tool"><h2>Call history</h2><p>Recent outgoing calls from your LayeredFX Twilio number.</p><Button variant="outline" disabled={!caps.voice} onClick={()=>void load()}>Refresh calls</Button>{error&&<p role="alert">{error}</p>}{!caps.voice&&<p>Connect Twilio to load call history.</p>}{caps.voice&&!calls.length&&<p>No outgoing calls found.</p>}{calls.map(c=><article className="quick-note" key={c.id}><b>{c.to}</b><small>{c.status} · {c.duration||0}s · {new Date(c.at).toLocaleString()}</small><Button size="sm" variant="outline" onClick={()=>onCall(c.to)}>Call back</Button></article>)}</div>;}
