"use client";
import {useState} from 'react';
import {ArrowLeft,ArrowRight,Search} from 'lucide-react';
import {Dialog,DialogContent,DialogDescription,DialogTitle} from '@/components/layeredfx/ui/dialog';
import {Button} from '@/components/layeredfx/ui/button';
import {useOperations} from './provider';
import {today} from '@/lib/operations/engine.mjs';
export {Button};
export const money=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n);
export const dateLabel=(date?:string|null)=>date?new Date(date.length===10?`${date}T12:00:00Z`:date).toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric',timeZone:'America/Phoenix'}):'Not set';
export function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="ops-field"><span>{label}</span>{children}</label>;}
export function Panel({title,children,action}:{title:string;children:React.ReactNode;action?:React.ReactNode}){return <section className="ops-panel"><div className="ops-panel-head"><h2>{title}</h2>{action}</div><div className="ops-panel-body">{children}</div></section>;}
export function PageTitle({eyebrow,title,description,children}:{eyebrow?:string;title:string;description:string;children?:React.ReactNode}){return <div className="ops-title"><div><p className="ops-eyebrow">{eyebrow||'LAYEREDFX / OPERATIONS'}</p><h1>{title}</h1><p>{description}</p></div><div className="ops-actions">{children}</div></div>;}
export function Empty({children}:{children:React.ReactNode}){return <div className="ops-empty">{children}</div>;}
export function SearchBox({value,onChange,placeholder='Search…'}:{value:string;onChange:(s:string)=>void;placeholder?:string}){return <label className="ops-search"><Search size={16}/><input aria-label={placeholder} placeholder={placeholder} value={value} onChange={e=>onChange(e.target.value)}/></label>;}
export function Views({values,value,onChange}:{values:string[];value:string;onChange:(v:string)=>void}){return <div className="ops-views" aria-label="View">{values.map(v=><button key={v} aria-pressed={value===v} className={value===v?'active':''} onClick={()=>onChange(v)}>{v}</button>)}</div>;}
export function Modal({title,description='Changes are saved to the current LayeredFX data mode.',open,onClose,children}:{title:string;description?:string;open:boolean;onClose:()=>void;children:React.ReactNode}){const {error,busy}=useOperations();return <Dialog open={open} onOpenChange={o=>!o&&onClose()}><DialogContent className="ops-modal"><DialogTitle>{title}</DialogTitle><DialogDescription>{description}</DialogDescription><div className="ops-form" aria-busy={busy}>{error&&<p className="ops-error" role="alert">{error}</p>}{children}</div></DialogContent></Dialog>;}
export function DownloadButton({name,data,label='Export JSON'}:{name:string;data:unknown;label?:string}){return <Button variant="outline" size="sm" onClick={()=>{const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}}>{label}</Button>;}
export function Calendar({records}:{records:{id:string;title:string;date:string;onClick:()=>void}[]}){
 const [month,setMonth]=useState(()=>today().slice(0,7));const first=new Date(`${month}-01T12:00:00`);const days=new Date(first.getFullYear(),first.getMonth()+1,0).getDate();const offset=first.getDay();const move=(n:number)=>{const d=new Date(first);d.setMonth(d.getMonth()+n);setMonth(`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`);};
 return <div className="ops-calendar-wrap"><div className="ops-toolbar"><Button size="icon" variant="outline" aria-label="Previous month" onClick={()=>move(-1)}><ArrowLeft size={16}/></Button><h2>{first.toLocaleDateString('en-US',{month:'long',year:'numeric'})}</h2><Button size="icon" variant="outline" aria-label="Next month" onClick={()=>move(1)}><ArrowRight size={16}/></Button></div><div className="ops-calendar">{['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map(d=><b key={d}>{d}</b>)}{Array.from({length:offset},(_,i)=><div key={`empty${i}`} className="muted"/>)}{Array.from({length:days},(_,i)=>{const day=`${month}-${String(i+1).padStart(2,'0')}`;return <div key={day}><span>{i+1}</span>{records.filter(r=>r.date===day).map(r=><button key={r.id} onClick={r.onClick}>{r.title}</button>)}</div>;})}</div>{records.some(r=>!r.date)&&<p className="ops-muted">{records.filter(r=>!r.date).length} records have no date and are not placed on this calendar.</p>}</div>;
}
