"use client";
import {useState} from 'react';
import Link from 'next/link';
import {usePathname} from 'next/navigation';
import {ArrowUpRight,ClipboardList,FileText,LayoutDashboard,Menu,TrendingUp,X} from 'lucide-react';
import {useOperations} from './provider';
import {Button,DownloadButton,PageTitle,Panel,money,dateLabel} from './shared';
import {needsNextStep,stats} from '@/lib/operations/engine.mjs';
const navigation=[{href:'/admin',label:'Overview',icon:LayoutDashboard},{href:'/admin/pipeline',label:'Pipeline',icon:TrendingUp},{href:'/admin/workspace',label:'Workspace',icon:FileText},{href:'/admin/plans',label:'Plans',icon:ClipboardList}];
export function OperationsShell({children}:{children:React.ReactNode}){const path=usePathname();const {actor,mode,state,busy,error,notice,reload,clearError}=useOperations();const [mobile,setMobile]=useState(false);return <div className="lfx ops" data-role={actor.role}><aside className={`ops-sidebar ${mobile?'is-open':''}`}><Link href="/admin" className="ops-brand">Layered<span>FX</span><small>THE OPERATIONS STUDIO</small></Link><button className="ops-mobile-close" aria-label="Close navigation" onClick={()=>setMobile(false)}><X/></button><p className="ops-sidebar-label">YOUR WORK</p><nav>{navigation.map(n=>{const Icon=n.icon;const active=n.href==='/admin'?path===n.href:path.startsWith(n.href);return <Link key={n.href} href={n.href} className={active?'active':''} aria-current={active?'page':undefined} onClick={()=>setMobile(false)}><Icon size={18}/>{n.label}{n.label==='Pipeline'&&<span>{state.deals.filter(d=>!d.archivedAt).length}</span>}</Link>;})}</nav><div className="ops-sidebar-bottom"><p>Beautiful work.<br/><b>Thoughtfully organized.</b></p><Link href="/">View website <ArrowUpRight size={15}/></Link><small>{mode==='demo'?'Local demonstration':'LayeredFX data connection'}</small></div></aside>{mobile&&<button className="ops-nav-backdrop" aria-label="Close navigation" onClick={()=>setMobile(false)}/>}<div className="ops-app"><header className="ops-topbar"><button className="ops-menu" aria-label="Open navigation" onClick={()=>setMobile(true)}><Menu size={22}/></button><div><b>LayeredFX</b><span className="ops-topbar-divider">/</span><span>Operations</span></div><div className="ops-user"><span className="ops-save-status" role="status">{busy?'Saving…':notice||'Ready'}</span><span className="ops-avatar">{actor.name.split(' ').map(x=>x[0]).slice(0,2).join('')}</span><span>{actor.name}<small>{actor.role}</small></span>{mode==='supabase'&&<button onClick={async()=>{await fetch('/api/operations/auth/logout',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});location.assign('/admin/login');}}>Sign out</button>}</div></header>{mode==='demo'&&<div className="ops-demo-banner"><b>LOCAL DEMO</b> Synthetic records. Changes stay in this browser. No messages, payments or bookings are sent.</div>}{error&&<div className="ops-global-error" role="alert"><p>{error}</p><div><button onClick={()=>void reload()}>Reload latest data</button><button onClick={clearError}>Dismiss</button></div></div>}<main className="ops-main" aria-busy={busy}>{children}</main><footer className="ops-app-footer">LayeredFX Operations · Pipeline / Workspace / Plans<span>{mode==='demo'?'Preview data':'Authenticated data'} · Revision {state.revision}</span></footer></div></div>;}
export function OperationsOverview(){const {state,actor,mode}=useOperations();const s=stats(state.deals);const activePlans=new Set(state.plans.filter(p=>!p.archived_at).map(p=>p.id));const tasks=state.tasks.filter(t=>activePlans.has(t.plan_id)&&t.status!=='complete');return <><PageTitle title="Make room for great work." description="Your opportunities, documents, and installation plans—connected in one place."><DownloadButton name="layeredfx-operations-export.json" data={{exportedAt:new Date().toISOString(),mode,state}} label="Export visible data"/></PageTitle><div className="ops-overview-hero"><div><p className="ops-eyebrow">THE NEXT LAYER</p><h2>From first conversation<br/>to the final finish.</h2><p>Know what comes next. Keep the context close.</p><Button asChild variant="light"><Link href="/admin/pipeline">Open pipeline <ArrowUpRight size={16}/></Link></Button></div><div className="ops-hero-metric"><span>Open opportunities</span><b>{money(s.openValue)}</b><small>{s.openCount} active opportunities</small></div></div><div className="ops-stats"><div><span>Needs a next step</span><b>{state.deals.filter(d=>!d.archivedAt&&needsNextStep(d)).length}</b></div><div><span>Workspace documents</span><b>{state.documents.filter(d=>!d.archived_at).length}</b></div><div><span>Active plans</span><b>{state.plans.filter(p=>!p.archived_at).length}</b></div><div><span>Open tasks</span><b>{tasks.length}</b></div></div><div className="ops-two-columns"><Panel title="Upcoming tasks" action={<Link href="/admin/plans">View plans</Link>}>{tasks.slice().sort((a,b)=>(a.due_date||'9999').localeCompare(b.due_date||'9999')).slice(0,6).map(t=><Link className="ops-record-row" key={t.id} href={`/admin/plans/${t.plan_id}`}><div><b>{t.title}</b><small>{state.plans.find(p=>p.id===t.plan_id)?.name}</small></div><span>{dateLabel(t.due_date)}</span></Link>)}{!tasks.length&&<p className="ops-muted">No open tasks yet.</p>}</Panel><Panel title="Your documents" action={<Link href="/admin/workspace">Open workspace</Link>}>{state.documents.filter(d=>!d.archived_at).slice(0,5).map(d=><Link className="ops-record-row" key={d.id} href={`/admin/workspace/${d.id}`}><FileText size={17}/><div><b>{d.title}</b><small>{d.owner_name} · {d.scope}</small></div><ArrowUpRight size={16}/></Link>)}<p className="ops-muted">Signed in as {actor.name}. Private documents and plans are filtered by access before being returned from the live API.</p></Panel></div></>;}
