"use client";
import {useEffect,useRef,useState} from 'react';
import {Mic,Square} from 'lucide-react';
import {Button,Field} from './shared';
import {useOperations} from './provider';
import {recordings,saveRecording,removeRecording,type LocalRecording} from '@/lib/communications/recordings';
function AudioFile({blob,name}:{blob:Blob;name:string}){const[url,setUrl]=useState('');useEffect(()=>{const next=URL.createObjectURL(blob);setUrl(next);return()=>URL.revokeObjectURL(next);},[blob]);return <><audio controls src={url||undefined} aria-label={name}/><a href={url||undefined} download={`${name.replace(/[^\w -]/g,'').slice(0,60)||'recording'}.${blob.type.includes('mp4')?'m4a':'webm'}`}>Download recording</a></>;}
export function VoiceRecorder(){
 const{actor}=useOperations();const[recording,setRecording]=useState(false),[pending,setPending]=useState(false),[error,setError]=useState(''),[blob,setBlob]=useState<Blob|null>(null),[name,setName]=useState('Voice note'),[saved,setSaved]=useState<LocalRecording[]>([]);
 const recorder=useRef<MediaRecorder|null>(null),stream=useRef<MediaStream|null>(null),timer=useRef<ReturnType<typeof setTimeout>|null>(null),mounted=useRef(true);
 useEffect(()=>{mounted.current=true;void recordings(actor.id).then(setSaved).catch(e=>setError(e.message));return()=>{mounted.current=false;if(timer.current)clearTimeout(timer.current);if(recorder.current?.state==='recording')recorder.current.stop();stream.current?.getTracks().forEach(t=>t.stop());};},[actor.id]);
 function stop(){if(recorder.current?.state==='recording')recorder.current.stop();stream.current?.getTracks().forEach(t=>t.stop());if(timer.current)clearTimeout(timer.current);setRecording(false);}
 async function start(){setError('');setPending(true);try{
  if(!navigator.mediaDevices?.getUserMedia||typeof MediaRecorder==='undefined')throw new Error('Microphone recording requires a supported browser on HTTPS or localhost.');
  const media=await navigator.mediaDevices.getUserMedia({audio:true});if(!mounted.current){media.getTracks().forEach(t=>t.stop());return;}stream.current=media;
  const mime=['audio/webm;codecs=opus','audio/webm','audio/mp4'].find(t=>MediaRecorder.isTypeSupported(t));const rec=new MediaRecorder(media,mime?{mimeType:mime}:undefined);recorder.current=rec;const chunks:Blob[]=[];let total=0;
  rec.ondataavailable=e=>{if(e.data.size){chunks.push(e.data);total+=e.data.size;if(total>=19_000_000&&rec.state==='recording')rec.stop();}};
  rec.onstop=()=>{media.getTracks().forEach(t=>t.stop());if(timer.current)clearTimeout(timer.current);if(mounted.current){setBlob(new Blob(chunks,{type:rec.mimeType}));setRecording(false);}};
  rec.onerror=()=>{media.getTracks().forEach(t=>t.stop());if(mounted.current){setError('Recording failed. Please check microphone access.');setRecording(false);}};
  setBlob(null);rec.start(1000);setRecording(true);timer.current=setTimeout(stop,180000);
 }catch(e){stream.current?.getTracks().forEach(t=>t.stop());setError(e instanceof Error?e.message:'Could not start microphone.');}finally{if(mounted.current)setPending(false);}}
 return <div className="quick-tool"><h2>Recordings &amp; microphone</h2><p>Record a voice note. Recordings stay on this browser until you download them; they are not uploaded or shared.</p><Field label="Recording name"><input value={name} onChange={e=>setName(e.target.value)} maxLength={100}/></Field><Button disabled={pending} onClick={()=>recording?stop():void start()}>{recording?<Square size={16}/>:<Mic size={16}/>} {pending?'Opening microphone…':recording?'Stop recording':'Start recording'}</Button>{recording&&<p role="status">Recording · stops automatically after 3 minutes. Close this tab to stop microphone access.</p>}{error&&<p role="alert" className="ops-error">{error}</p>}{blob&&<div className="quick-recording"><AudioFile blob={blob} name={name}/><Button variant="outline" disabled={!name.trim()} onClick={async()=>{try{await saveRecording({id:crypto.randomUUID(),ownerId:actor.id,name:name.trim(),createdAt:new Date().toISOString(),blob});setSaved(await recordings(actor.id));setBlob(null);}catch(e){setError(e instanceof Error?e.message:'Could not save recording.');}}}>Save in this browser</Button><button onClick={()=>setBlob(null)}>Discard recording</button></div>}<h3>Saved on this browser</h3>{!saved.length&&<p>No saved recordings.</p>}{saved.slice().reverse().map(r=><article className="quick-recording" key={r.id}><b>{r.name}</b><small>{new Date(r.createdAt).toLocaleString()}</small><AudioFile blob={r.blob} name={r.name}/><button onClick={async()=>{if(confirm('Delete this local recording?')){try{await removeRecording(r.id,actor.id);setSaved(await recordings(actor.id));}catch(e){setError(e instanceof Error?e.message:'Delete failed.');}}}}>Delete recording</button></article>)}</div>;
}
