import 'server-only';
import {mkdir,readFile,readdir,writeFile} from 'node:fs/promises';
import path from 'node:path';
import {mode,configured,currentActor} from '@/lib/operations/server';
import {OperationError} from '@/lib/operations/engine.mjs';
import {isUuid} from '@/lib/operations/security.mjs';
import {metadata,type Intake} from './model';
const directory=()=>path.join(process.cwd(),'.local-data','contact-submissions');
export async function intakeAccess(){if(mode()!=='demo'){const actor=await currentActor();if(actor.role==='viewer')throw new OperationError('Staff access required.',403);}}
async function db(query:string,init:RequestInit={}){if(!configured()||!isUuid(process.env.LFX_OPERATIONS_ORG_ID))throw new OperationError('Contact storage is not configured. Please call or email us.',503);const response=await fetch(`${process.env.LFX_SUPABASE_URL}/rest/v1/lfx_contact_submissions?org_id=eq.${process.env.LFX_OPERATIONS_ORG_ID}${query}`,{...init,headers:{apikey:process.env.LFX_SUPABASE_SERVICE_ROLE_KEY!,Authorization:`Bearer ${process.env.LFX_SUPABASE_SERVICE_ROLE_KEY!}`,'Content-Type':'application/json',...init.headers},cache:'no-store',signal:AbortSignal.timeout(15000)});if(!response.ok)throw new OperationError(response.status===409?'This request was already received.':'Contact storage is unavailable. Please call or email us.',response.status===409?409:503);return response;}
export async function saveIntake(item:Intake){if(mode()==='demo'){await mkdir(directory(),{recursive:true});if((await readdir(directory())).length>=1000)throw new OperationError('The local inbox is full.',503);try{await writeFile(path.join(directory(),item.id+'.json'),JSON.stringify(item),{flag:'wx'});}catch(e){if((e as NodeJS.ErrnoException).code==='EEXIST')throw new OperationError('This request was already received.',409);throw e;}}else await db('',{method:'POST',body:JSON.stringify({org_id:process.env.LFX_OPERATIONS_ORG_ID,id:item.id,created_at:item.createdAt,details:metadata(item),files:item.files})});}
export async function getIntake(id:string):Promise<Intake>{if(!isUuid(id))throw new OperationError('Invalid submission.',400);if(mode()==='demo'){try{return JSON.parse(await readFile(path.join(directory(),id+'.json'),'utf8'));}catch(e){if((e as NodeJS.ErrnoException).code==='ENOENT')throw new OperationError('Submission not found.',404);throw e;}}const rows=await(await db(`&id=eq.${id}&select=details,files`)).json();if(!rows[0])throw new OperationError('Submission not found.',404);return {...rows[0].details,files:rows[0].files};}
export async function listIntake(offset=0):Promise<Intake[]>{if(mode()==='demo'){let names:string[];try{names=await readdir(directory());}catch(e){if((e as NodeJS.ErrnoException).code==='ENOENT')return [];throw e;}const items=await Promise.all(names.filter(n=>/^[a-f0-9-]{36}\.json$/i.test(n)).map(n=>getIntake(n.slice(0,-5))));return items.sort((a,b)=>b.createdAt.localeCompare(a.createdAt)).slice(offset,offset+50).map(metadata);}const rows=await(await db(`&select=details&order=created_at.desc&limit=50&offset=${offset}`)).json();return rows.map((row:{details:Intake})=>row.details);}
