'use client';
import {useEffect,useState} from 'react';
import {AdminContent} from '@/ctrlp/components/admin/admin-content';
import {SourceScreen} from './source-screen';
import type {Notice,NoticeState} from '@/lib/topbar/model';
const blank={title:'',message:'',link:'',linkLabel:'',status:'draft' as Notice['status'],start:'',end:'',priority:0};
export function ContentTabs(){const [tab,setTab]=useState('content'),[state,setState]=useState<NoticeState>({revision:0,items:[]}),[form,setForm]=useState<Partial<Notice>>(blank),[error,setError]=useState(''),[ready,setReady]=useState(false),[busy,setBusy]=useState(false);
 async function refresh(){const r=await fetch('/api/topbar/manage');const d=await r.json();if(!r.ok)throw Error(d.message||'Could not load notifications');setState(d);setReady(true);}
 useEffect(()=>{refresh().catch(e=>setError(e.message));},[]);
 async function save(method:string,id?:string){setBusy(true);setError('');try{const r=await fetch('/api/topbar/manage',{method,headers:{'Content-Type':'application/json'},body:JSON.stringify({...form,id:id||form.id,revision:state.revision})});const d=await r.json();if(!r.ok)throw Error(d.message||'Could not save');await refresh();setForm(blank);}catch(e){setError(e instanceof Error?e.message:'Could not save');}finally{setBusy(false);}}
 return <div><div className="content-tabs" role="tablist" aria-label="Content management">{[['content','Content'],['topbar','Top Bar Notifications']].map(([id,label])=><button key={id} role="tab" aria-selected={tab===id} onClick={()=>setTab(id)}>{label}</button>)}</div>{tab==='content'?<SourceScreen><AdminContent/></SourceScreen>:<section className="topbar-manager"><h1>Top Bar Notifications</h1><p>Schedule messages above the frontend navigation. Highest priority wins when schedules overlap. Times use Arizona (America/Phoenix). Changes appear within 30 seconds.</p>{error&&<p role="alert">{error} <button onClick={()=>refresh().catch(e=>setError(e.message))}>Reload</button></p>}<div className="topbar-manager-grid"><form onSubmit={e=>{e.preventDefault();void save(form.id?'PATCH':'POST');}}><h2>{form.id?'Edit notification':'New notification'}</h2>{[['title','Internal title',100],['message','Public message',240],['link','Link URL (optional)',500],['linkLabel','Link text',80]].map(([key,label,max])=><label key={key}>{label}<input required={key==='title'||key==='message'} maxLength={Number(max)} value={String(form[key as keyof Notice]||'')} onChange={e=>setForm({...form,[key]:e.target.value})}/></label>)}<label>Status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value as Notice['status']})}><option value="draft">Draft</option><option value="published">Published / scheduled</option><option value="archived">Archived</option></select></label>{[['start','Start date & time'],['end','End date & time']].map(([key,label])=><label key={key}>{label}<input type="datetime-local" value={String(form[key as keyof Notice]||'').slice(0,16)} onChange={e=>setForm({...form,[key]:e.target.value})}/></label>)}<p>Leave dates empty to publish immediately without an end date. Drafts and archived messages never appear.</p><label>Priority (0-100)<input type="number" min="0" max="100" value={form.priority} onChange={e=>setForm({...form,priority:+e.target.value})}/></label><button disabled={!ready||busy} type="submit">Save notification</button><button type="button" onClick={()=>setForm(blank)}>Clear form</button></form><div><h2>Notifications</h2>{state.items.length===0&&<p>No notifications yet. The default brand message is shown.</p>}{state.items.map(n=><article key={n.id}><h3>{n.title}</h3><p>{n.message}</p><small>{n.status} / Priority {n.priority}<br/>{n.start||'Immediately'} to {n.end||'No end date'}</small><div><button disabled={busy} onClick={()=>setForm(n)}>Edit</button><button disabled={busy} onClick={()=>{if(confirm('Delete this notification?'))void save('DELETE',n.id);}}>Delete</button></div></article>)}</div></div></section>}</div>;
}
