import {currentPortal,portalClient,savePortal,portalAccount} from '@/lib/portal/server';
import {checkOrigin,errorResponse,currentActor} from '@/lib/operations/server';
import {OperationError} from '@/lib/operations/engine.mjs';
const bucket='lfx-portal-media';
export async function GET(request:Request){try{const userId=new URL(request.url).searchParams.get('account');let account;if(userId){const actor=await currentActor();if(actor.role==='viewer')throw new OperationError('Staff access required.',403);if(!/^[0-9a-f-]{36}$/i.test(userId))throw new OperationError('Invalid account.',400);account=await portalAccount(userId);}else account=await currentPortal();if(account.status!=='active')throw new OperationError('Active access required.',403);const file=account.state.media.find(f=>f.id===new URL(request.url).searchParams.get('id'));if(!file)throw new OperationError('Media not found.',404);const{data,error}=await portalClient(true).storage.from(bucket).createSignedUrl(file.path,60);if(error)throw new OperationError('Could not open media.',503);return Response.json({url:data.signedUrl},{headers:{'Cache-Control':'private, no-store'}});}catch(e){return errorResponse(e);}}
export async function POST(request:Request){try{checkOrigin(request);const account=await currentPortal();if(account.status!=='active')throw new OperationError('Active access required.',403);if(Number(request.headers.get('x-portal-revision'))!==account.revision)throw new OperationError('Reload before uploading.',409);if(account.state.media.length>=100)throw new OperationError('Media limit reached.',400);
 let name;try{name=decodeURIComponent(request.headers.get('x-file-name')||'Media').slice(0,180);}catch{throw new OperationError('Invalid filename.',400);}
 const type=request.headers.get('content-type')||'';if(!['image/jpeg','image/png','image/webp','video/mp4','video/webm'].includes(type))throw new OperationError('Use JPEG, PNG, WebP, MP4 or WebM.',400);
 const reader=request.body?.getReader();if(!reader)throw new OperationError('Choose a file.',400);const chunks:Uint8Array[]=[];let size=0;while(true){const{value,done}=await reader.read();if(done)break;size+=value.byteLength;if(size>20*1024*1024){await reader.cancel();throw new OperationError('Files must be under 20 MB.',413);}chunks.push(value);}if(!size)throw new OperationError('File is empty.',400);const bytes=Buffer.concat(chunks);
 const valid=type==='image/jpeg'?bytes[0]===255&&bytes[1]===216:type==='image/png'?bytes.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10])):type==='image/webp'?bytes.toString('ascii',0,4)==='RIFF'&&bytes.toString('ascii',8,12)==='WEBP':type==='video/mp4'?bytes.toString('ascii',4,8)==='ftyp':bytes.subarray(0,4).equals(Buffer.from([26,69,223,163]));if(!valid)throw new OperationError('File content does not match its media type.',400);
 const id=crypto.randomUUID(),path=`${account.org_id}/${account.user_id}/${id}`;const storage=portalClient(true).storage.from(bucket);const{error}=await storage.upload(path,bytes,{contentType:type,upsert:false});if(error)throw new OperationError('Upload failed. Check the private portal media bucket.',503);
 const next=structuredClone(account);next.state.media.push({id,path,type,size,name});next.revision++;
 try{await savePortal(next,account.revision);}catch(e){await storage.remove([path]);throw e;}return Response.json(next,{headers:{'Cache-Control':'private, no-store'}});
 }catch(e){return errorResponse(e);}}
