import {chromium} from 'playwright';import fs from 'node:fs';
const browser=await chromium.launch({channel:'msedge',headless:true,args:['--use-fake-device-for-media-stream','--use-fake-ui-for-media-stream']});
const context=await browser.newContext({viewport:{width:1440,height:1000},permissions:['microphone']});
await context.addInitScript(()=>{Object.defineProperty(window,'ContactsManager',{value:function(){}});Object.defineProperty(navigator,'contacts',{value:{select:async()=>Array.from({length:205},(_,i)=>({name:[`Android Review ${i}`],email:[`android${i}@example.test`],tel:[`+1480555${String(i).padStart(4,'0')}`]}))}});});
const page=await context.newPage();page.setDefaultTimeout(15000);const checks=[],errors=[];page.on('pageerror',e=>errors.push(e.message));
const consoleErrors=[];page.on('console',message=>{if(message.type()==='error')consoleErrors.push(message.text());});
try{
 await page.goto('http://127.0.0.1:3000/admin/contacts');await page.getByRole('heading',{name:'Contacts',exact:true}).waitFor();
 await page.getByRole('button',{name:'Add contact',exact:true}).click();const editor=page.getByRole('dialog',{name:'Add contact',exact:true});
 await editor.getByLabel('Full name',{exact:true}).fill('Jordan Browser Review');await editor.getByLabel('Email',{exact:true}).fill('jordan.browser@example.test');await editor.getByLabel('Phone',{exact:true}).fill('+14805559999');await editor.getByRole('button',{name:'Save contact',exact:true}).click();
 const detail=page.getByRole('dialog',{name:'Jordan Browser Review',exact:true});await detail.waitFor();await detail.getByRole('button',{name:'Work Lead',exact:true}).click();await detail.getByRole('link',{name:'Lead: Jordan Browser Review'}).waitFor();
 await detail.getByLabel('Linked user').click();await page.getByRole('option',{name:'Demo Installer (staff)',exact:true}).click();await detail.getByRole('button',{name:'Save user link'}).click();await detail.getByLabel('Activity text').fill('Contact reviewed in browser test.');await detail.getByRole('button',{name:'Log activity'}).click();await detail.getByText('Contact reviewed in browser test.',{exact:true}).waitFor();
 await detail.getByRole('button',{name:'Add to Pipeline',exact:true}).click();await page.waitForURL('**/admin/pipeline/*');const pipeline=page.url();
 let saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('layeredfx:operations:v2')));const contact=saved.contacts.find(c=>c.email==='jordan.browser@example.test');const lead=saved.leads.find(l=>l.contactId===contact.id);checks.push({name:'Contact, lead, user and pipeline share canonical identity',passed:contact.userId==='demo_staff'&&saved.deals.find(d=>d.id===lead.opportunityId)?.contactId===contact.id});
 await page.goto('http://127.0.0.1:3000/admin/contacts');await page.getByRole('button',{name:'From phone',exact:true}).click();const importer=page.getByRole('dialog',{name:'Import contacts',exact:true});await importer.getByRole('button',{name:'Choose from Android phone'}).click();await importer.getByRole('button',{name:'Deselect all',exact:true}).click();await importer.getByRole('button',{name:'Select all contacts',exact:true}).click();await importer.getByRole('button',{name:'Import 205 selected contacts',exact:true}).waitFor();await page.screenshot({path:'docs/reviews/screenshots/contacts-select-all.png'});
 await importer.getByRole('button',{name:'Import 205 selected contacts',exact:true}).click();await importer.waitFor({state:'hidden'});await page.reload();await page.getByRole('heading',{name:'Contacts',exact:true}).waitFor();saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('layeredfx:operations:v2')));checks.push({name:'Select all phone contacts imports across multiple batches and survives reload',passed:saved.contacts.filter(c=>c.email.startsWith('android')).length===205});
 for(const name of ['List','Table','Cards','Kanban','Calendar']){await page.getByRole('button',{name,exact:true}).click();checks.push({name:'Contacts '+name,passed:true});}
 await page.getByRole('button',{name:'List',exact:true}).click();await page.screenshot({path:'docs/reviews/screenshots/contacts-desktop.png'});
 await page.getByRole('button',{name:'Quick actions',exact:true}).click();const fab=page.getByRole('dialog',{name:'Quick actions',exact:true});await fab.getByRole('tab',{name:'Notes',exact:true}).click();await fab.getByLabel('Title',{exact:true}).fill('Private browser note');await fab.getByLabel('Note',{exact:true}).fill('Remember the kitchen measurements.');await fab.getByRole('button',{name:'Save note',exact:true}).click();await fab.getByText('Private browser note',{exact:true}).waitFor();
 await fab.getByRole('tab',{name:'Direct messages',exact:true}).click();await fab.getByLabel('Recipient').click();await page.getByRole('option',{name:'Demo Installer',exact:true}).click();await fab.getByLabel('Message',{exact:true}).fill('Preview direct message');await fab.getByRole('button',{name:'Save preview message',exact:true}).click();await fab.getByText('Preview direct message',{exact:true}).waitFor();checks.push({name:'FAB private notes and preview direct message persist',passed:true});
 for(const name of ['AI Agents','SMS','Dialpad','Call history']){await fab.getByRole('tab',{name,exact:true}).click();checks.push({name:'FAB '+name,passed:true});}
 await fab.getByRole('tab',{name:'Dialpad',exact:true}).click();await fab.getByLabel('Phone number',{exact:true}).fill('+14805550123');checks.push({name:'Unconfigured Twilio cannot call',passed:await fab.getByRole('button',{name:'Call with Twilio'}).isDisabled()});await page.screenshot({path:'docs/reviews/screenshots/fab-dialpad.png'});
 await fab.getByRole('tab',{name:'Recordings / Microphone',exact:true}).click();await fab.getByRole('button',{name:'Start recording',exact:true}).click();await fab.getByRole('button',{name:'Stop recording',exact:true}).waitFor();await page.waitForTimeout(1200);await fab.getByRole('button',{name:'Stop recording',exact:true}).click();await fab.getByRole('button',{name:'Save in this browser',exact:true}).click();await fab.getByRole('button',{name:'Delete recording',exact:true}).waitFor();checks.push({name:'Synthetic microphone recording saved to browser',passed:true});
 await fab.getByRole('button',{name:'Close quick actions',exact:true}).click();await page.setViewportSize({width:390,height:844});await page.getByRole('button',{name:'Quick actions',exact:true}).click();await fab.getByRole('tab',{name:'Dialpad',exact:true}).click();await page.screenshot({path:'docs/reviews/screenshots/fab-mobile.png'});checks.push({name:'Mobile FAB fits viewport',passed:await fab.evaluate(e=>e.getBoundingClientRect().right<=window.innerWidth&&e.getBoundingClientRect().left>=0)});
 await fab.getByRole('button',{name:'Close quick actions',exact:true}).click();await page.goto(pipeline);await page.locator('h1').first().waitFor();checks.push({name:'Existing opportunity remains accessible',passed:true});
}finally{fs.writeFileSync('docs/reviews/logs/contacts-browser.json',JSON.stringify({checks,errors,consoleErrors},null,2));await browser.close();}
console.log(JSON.stringify({checks,errors},null,2));if(errors.length||checks.some(c=>!c.passed))process.exitCode=1;
