import {chromium} from 'playwright';import assert from 'node:assert/strict';import {writeFileSync} from 'node:fs';
const browser=await chromium.launch({channel:'msedge',headless:true});const page=await browser.newPage({viewport:{width:1440,height:1000},reducedMotion:'reduce'});const errors=[];page.on('pageerror',e=>errors.push(e.message));
try{
 await page.goto('http://127.0.0.1:3000/login');await page.getByRole('heading',{name:'Welcome back.'}).waitFor();await page.screenshot({path:'docs/reviews/screenshots/portal-login.png'});
 await page.goto('http://127.0.0.1:3000/register');await page.getByRole('combobox').click();await page.getByRole('option',{name:'General contractor',exact:true}).click();await page.getByText('Partner accounts are reviewed by our team before access is approved.').waitFor();await page.screenshot({path:'docs/reviews/screenshots/portal-register.png'});
 await page.goto('http://127.0.0.1:3000/portal/bookings');await page.getByRole('button',{name:'New request',exact:true}).click();await page.getByLabel('Title',{exact:true}).fill('Kitchen consultation');await page.getByLabel('Details',{exact:true}).fill('Review cabinet finishes and installation.');await page.getByRole('button',{name:'Save preview',exact:true}).click();await page.getByText('Kitchen consultation',{exact:true}).waitFor();await page.reload();await page.getByText('Kitchen consultation',{exact:true}).waitFor();
 await page.goto('http://127.0.0.1:3000/portal/messages');await page.getByRole('button',{name:'New message',exact:true}).click();await page.getByLabel('Title',{exact:true}).fill('Finish question');await page.getByLabel('Details',{exact:true}).fill('Can we review samples?');await page.getByRole('button',{name:'Save preview',exact:true}).click();await page.getByText('Finish question',{exact:true}).waitFor();
 await page.goto('http://127.0.0.1:3000/portal/media');await page.locator('input[type=file]').setInputFiles('public/brand/LayeredFX_favicon_light.png');await page.getByAltText('LayeredFX_favicon_light.png').waitFor();await page.reload();await page.getByAltText('LayeredFX_favicon_light.png').waitFor();
 await page.goto('http://127.0.0.1:3000/portal/profile');await page.getByLabel('Name',{exact:true}).fill('Review Customer');await page.getByRole('button',{name:'Save profile'}).click();await page.getByRole('status').waitFor();await page.reload();await page.waitForFunction(()=>document.querySelector('input[name=name]')?.value==='Review Customer');assert.equal(await page.getByLabel('Name',{exact:true}).inputValue(),'Review Customer');
 for(const section of ['products','services','notes']){await page.goto(`http://127.0.0.1:3000/portal/${section}`);await page.locator('h1').waitFor();}
 await page.goto('http://127.0.0.1:3000/portal');await page.screenshot({path:'docs/reviews/screenshots/portal-customer.png'});
 await page.goto('http://127.0.0.1:3000/partner');await page.getByRole('heading',{name:'Your partner workspace.'}).waitFor();await page.screenshot({path:'docs/reviews/screenshots/portal-partner.png'});
 await page.goto('http://127.0.0.1:3000/partner/referrals');await page.getByRole('button',{name:'New request'}).click();await page.getByLabel('Title',{exact:true}).fill('Office project referral');await page.getByLabel('Details',{exact:true}).fill('Commercial office consultation request.');await page.getByRole('button',{name:'Save preview'}).click();await page.getByText('Office project referral',{exact:true}).waitFor();
 await page.getByRole('button',{name:'Toggle portal theme'}).click();await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.screenshot({path:'docs/reviews/screenshots/portal-mobile-dark.png'});
 await page.goto('http://127.0.0.1:3000/');await page.locator('.lfx-account summary').click();await page.getByRole('link',{name:'Login',exact:true}).click();await page.waitForURL('**/login');await page.screenshot({path:'docs/reviews/screenshots/portal-login-mobile.png'});
 assert.deepEqual(errors,[]);writeFileSync('docs/reviews/logs/portal-browser.json',JSON.stringify({passed:true,checks:['login registration layout','partner approval notice','booking request persists','DM persists','media persists in IndexedDB','profile persists','catalog and service screens','separate partner preview','referral request','mobile dark theme no overflow','homepage mobile sign-in link'],errors},null,2));console.log('Portal browser checks passed.');
}finally{await browser.close();}
