import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import {writeFileSync} from 'node:fs';
const browser=await chromium.launch({channel:'msedge',headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1000}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
try {
 await page.goto('http://127.0.0.1:3000/admin');
 const collapse=page.getByRole('button',{name:'Collapse sidebar',exact:true});
 await collapse.click();
 const expand=page.getByRole('button',{name:'Expand sidebar',exact:true});
 await expand.waitFor();
 assert.equal(await expand.getAttribute('aria-expanded'),'false');
 assert.equal(await page.locator('.ops-sidebar').evaluate(e=>e.getBoundingClientRect().width),76);
 assert.equal(await page.locator('.ops-app').evaluate(e=>e.getBoundingClientRect().left),76);
 const nav=page.getByRole('navigation',{name:'Dashboard navigation'});
 assert.equal(await nav.evaluate(e=>getComputedStyle(e).scrollbarWidth),'thin');
 await nav.getByRole('link',{name:'Contacts',exact:true}).click();
 await page.waitForURL('**/admin/contacts');
 await page.reload();await expand.waitFor();
 await page.screenshot({path:'docs/reviews/screenshots/sidebar-collapsed.png'});
 const last=nav.getByRole('link').last();await last.focus();
 assert.equal(await last.evaluate(e=>e===document.activeElement),true);
 await expand.focus();await page.keyboard.press('Enter');await collapse.waitFor();
 assert.equal(await page.locator('.ops-sidebar').evaluate(e=>e.getBoundingClientRect().width),248);
 await page.screenshot({path:'docs/reviews/screenshots/sidebar-expanded.png'});
 await collapse.click();
 await page.setViewportSize({width:390,height:844});
 await page.getByRole('button',{name:'Open navigation',exact:true}).click();
 assert.equal(await nav.getByRole('link',{name:'Contacts',exact:true}).locator('.ops-nav-text').isVisible(),true);
 assert.equal(await expand.isVisible(),false);
 await page.screenshot({path:'docs/reviews/screenshots/sidebar-mobile.png'});
 await nav.getByRole('link',{name:'Dashboard',exact:true}).click();
 await page.waitForURL('**/admin');
 assert.equal(await page.locator('.ops-sidebar').evaluate(e=>e.classList.contains('is-open')),false);
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 await page.goto('http://127.0.0.1:3000/');await page.locator('.lfx-logo').first().waitFor();
 assert.deepEqual(errors,[]);
 writeFileSync('docs/reviews/logs/sidebar-browser.json',JSON.stringify({passed:true,checks:['collapse and content resize','thin scrollbar','icon navigation','reload persistence','keyboard expand and last link focus','expanded width','full mobile menu','mobile navigation closes menu','no mobile overflow','homepage renders'],errors},null,2));
 console.log('Sidebar browser checks passed.');
} finally {await browser.close();}
